### ISSUE TITLE
Session Cookie is not added in the response when using Tiles and Tomcat 8

### ISSUE THREAD

**Issue by codependent** [spring-projects/spring-session#571] opened 2016-07-14 08:09 UTC
I opened a [question on Stackoverflow](http://stackoverflow.com/questions/38368151/spring-session-not-working-on-tomcat-8-when-using-tiles-session-cookie-is-not) where you can find a complete description of the problem.

To sum up, when using Tiles, Tomcat's HttpServletReponse addCookie() checks that the response is not included. If it is, it doesn't add the cookie so the created session doesn't reach the browser.

Any idea of how this could be addressed?

**Comment by kazuki43zoo** [comment] 2016-12-02 08:07
+1

The same problem has occurred in my application.

**Comment by ikeyat** [comment] 2016-12-05 01:20
+1

**Comment by jhkim105** [comment] 2017-02-10 13:37
+1

**Comment by wanderg84** [comment] 2017-10-31 09:32
+1

**Comment by rwinch** [comment] 2017-10-31 21:30
I am unable to reproduce this. Can someone create a sample that demonstrates the problem?

**Comment by vpavic** [comment] 2019-01-20 12:15
I believe this is the same issue as #1214, which was resolved by #1243 in Spring Session `2.1.2.RELEASE` and backported to `2.0.8.RELEASE` and `1.3.4.RELEASE` via #1244 and #1250, respectively.

**Closed by vpavic** 2019-01-20 12:15 UTC
Labels: waiting for feedback

**Comment by vpavic** [comment] 2019-01-20 17:39
Duplicate of #1214
