### ISSUE TITLE
Unable to obtain SessionCookieConfig

### ISSUE THREAD

**Issue by lglapinski** [spring-projects/spring-session#1040] opened 2018-04-09 17:02 UTC
Hi!

I have following configuration:

spring - 5.0.5
spring session - 5.0.4
spring session data redis - 2.0.2

During each deployment I see this: 

```
WARN  RedisHttpSessionConfiguration$$EnhancerBySpringCGLIB$$35c2575f:174 - Unable to obtain SessionCookieConfig: Section 4.4 of the Servlet 3.0 specification does not permit this method to be called from a ServletContextListener that was not defined in web.xml, a web-fragment.xml file nor annotated with @WebListener
```

Configuration:

```
public class SecurityInitializer extends AbstractSecurityWebApplicationInitializer {
}
```

```
public class SessionInitializer extends AbstractHttpSessionApplicationInitializer {
}
```

```
public class WebAppInitializer extends AbstractAnnotationConfigDispatcherServletInitializer {

    @Override
    protected Class<?>[] getRootConfigClasses() {
        return new Class<?>[]{AppConfig.class, AsyncConfig.class, PersistenceConfig.class, RedisConfig.class,
                SchedulingConfig.class, SecurityConfig.class, WebMvcConfig.class};
    }

    @Override
    protected Class<?>[] getServletConfigClasses() {
        return null;
    }

    @Override
    protected String[] getServletMappings() {
        return new String[]{"/"};
    }

    @Override
    protected Filter[] getServletFilters() {
        return new Filter[]{
                new CharacterEncodingFilter("UTF-8", true)
        };
    }

```

```
@Configuration
@EnableRedisHttpSession
public class RedisConfig {
    @Value("${REDIS_ENDPOINT:localhost}")
    private String redisEndpoint;

    @Value("${REDIS_PORT:6379}")
    private Integer redisPort;

    @Bean
    public ConfigureRedisAction configureRedisAction() {
        return ConfigureRedisAction.NO_OP;
    }

    @Bean
    public LettuceConnectionFactory connectionFactory() {
        return new LettuceConnectionFactory(new RedisStandaloneConfiguration(redisEndpoint, redisPort));
    }

    @Bean
    RedisSerializer<Object> springSessionDefaultRedisSerializer() {
        return new CustomRedisSerializer();
    }
}
```

**Comment by vpavic** [comment] 2018-04-18 19:42
Thanks for the report @lglapinski. Could you provide a sample app that we can use to reproduce this issue? Also which servlet container are you running your app in?

**Comment by lglapinski** [comment] 2018-04-23 18:10
It's Apache Tomcat/8.0.47

**Comment by vpavic** [comment] 2019-01-12 21:11
This issue can be reproduced using Spring Session's Java config based sample apps.

**Comment by vpavic** [comment] 2019-01-29 00:05
As this works in app with XML based config, it appears the problem might be in Spring Framework - I've opened spring-projects/spring-framework#22319.

**Comment by vpavic** [comment] 2019-01-29 14:41
Since this really appears to be a limitation in Spring Framework, I'm going to close this one as duplicate - please track spring-projects/spring-framework#22319 for further developments.

**Closed by vpavic** 2019-01-29 14:41 UTC
Labels: bug
