### ISSUE TITLE
Spring session in IBM Websphere

### ISSUE THREAD

**Issue by Bubai14** [spring-projects/spring-session#1557] opened 2020-01-06 14:06 UTC
We are trying to integrate Spring session with an application built on Struts 2 and running on IBM Websphere Application Server 8.5.5.12. We created a sample struts 2 application and executed in Tomcat integrating Spring session. It worked fine. But it is not working in IBM Websphere Application Server. The issue we are facing is the application is not creating the SESSION cookie in IBM Websphere whereas it is getting created in Tomcat. Please provide any direction whether we need to invest any further efforts on this.

**Comment by vpavic** [comment] 2020-01-10 17:31
I'm afraid there's not enough information here in order for us to be able to help you. Can you provide a sample that can be used to reproduce the problem?

**Comment by spring-issuemaster** [comment] 2020-01-17 17:33
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-24 17:33
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-24 17:33 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
