### ISSUE TITLE
Support for servlet 3.1 API of request.changeSessionId()

### ISSUE THREAD

**Issue by prasenjit-net** [spring-projects/spring-session#180] opened 2015-04-07 04:12 UTC
Servlet API 3.1 has added one API changeSessionId() to defend against session fixation. Please add that support in here too.

**Comment by cemo** [comment] 2015-04-07 04:57
see #152

**Comment by rwinch** [comment] 2015-04-07 13:34
Thanks for the report @prasenjit-net This is indeed a duplicate of #152 Please give the 1.0.1.BUILD-SNAPSHOT a try from https://repo.spring.io/snapshots and let me know if you are still having problems.

**Closed by rwinch** 2015-04-07 13:34 UTC
Labels: duplicate
