### ISSUE TITLE
why RedisSessionExpirationPolicy#onDelete remove something not exist in the expirations SET?

### ISSUE THREAD

**Issue by Alwayswithme** [spring-projects/spring-session#1531] opened 2019-10-08 06:33 UTC
the spring:session:expirations:${roundUpToNextMinute}  redis SET is store value call keyToExpire:
```
		String expireKey = getExpirationKey(toExpire);
		BoundSetOperations<Object, Object> expireOperations = this.redis.boundSetOps(expireKey);
		expireOperations.add(keyToExpire);
```
the keyToExpire is a string like expires:${sessionId}
https://github.com/spring-projects/spring-session/blob/927008bdc89701555f2f8f900f4f898df23b1476/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionExpirationPolicy.java#L97

however, when delete the session, it actually remove the session id not expires:${sessionId}
```
	this.redis.boundSetOps(expireKey).remove(session.getId());
```

https://github.com/spring-projects/spring-session/blob/927008bdc89701555f2f8f900f4f898df23b1476/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisSessionExpirationPolicy.java#L70

Is this a defact or My misunderstanding?

**Comment by vpavic** [comment] 2019-10-09 14:32
The behavior of session expiration handling for Redis session repository is described both in the `RedisOperationsSessionRepository` javadoc and [reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-storage).

Are you experiencing any particular issue here?

**Comment by Alwayswithme** [comment] 2019-10-10 07:31
org.springframework.session.data.redis.RedisOperationsSessionRepository#delete will delete the expireKey,

**Comment by Alwayswithme** [comment] 2020-01-18 04:28
@vpavic please take a look

**Comment by eleftherias** [comment] 2021-03-12 14:30
Thanks for the report @Alwayswithme. 
I'm going to close this issue as a duplicate of gh-585.
Please follow gh-585 for updates.

**Closed by eleftherias** 2021-03-12 14:30 UTC
Labels: status: feedback-provided
