### ISSUE TITLE
session timeout wrong behavior

### ISSUE THREAD

**Issue by nagyzsolthun** [spring-projects/spring-session#1098] opened 2018-06-09 10:56 UTC
I have a very simple example project that uses spring-sessions: https://github.com/nagyzsolthun/spring-boot-session-destroy.

I would like to execute a certain logic when a session is destroyed, so I would expect the following behavior at session timeout (set to 10 seconds in my project):
1. session scoped beans get destroyed
1. session data is removed from redis
1. matching behavior in eclipse IDE and when running from console with ```gradle bootRun```

However, when running this example, I see the see the following behavior:
1. session scoped beans never gets destroyed
1. redis record with key spring:session:sessions[UUID] stays forever
1. no session timeout when running with ```gradle bootRun```

**Comment by vpavic** [comment] 2018-06-13 19:15
Thanks for the report @nagyzsolthun and providing the sample app upfront, we really appreciate that.

There are several things going on here:

- your `application.properties` is located in `src/resources` instead of `src/main/resources` so `server.servlet.session.timeout` application property isn't applied (I'm not using Eclipse so I don't know how it works there) - I've opened nagyzsolthun/spring-boot-session-destroy#1 against your repo to address that
- session data stays in Redis for 5 minutes after session session has expired, for purpose of processing session events - this behavior is explained both in `RedisOperationsSessionRepository` javadoc and in our [reference manual](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-redisoperationssessionrepository-expiration)
- `@PreDestroy` on session scoped bean isn't invoked since Spring Session doesn't support `HttpSessionBindingListener` (which `DestructionCallbackBindingListener` implements) yet - but we plan to, please track #1018

With that, I'm going to close this as duplicate of #1018, as other points of the report are invalid.

**Comment by vpavic** [comment] 2018-06-13 19:15
Duplicate of #1018

**Closed** 2018-06-13 19:16 UTC
Labels: duplicate

**Comment by nagyzsolthun** [comment] 2018-09-16 13:50
Thank you for the info and the fixes. Since #1018 was closed in July, I'm trying to run this example project again, with a newer Spring version (2.0.5). However, I'm facing a different issue this time.

I see this exception when sending in a HTTP request:
```org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: org.springframework.security.core.context.SecurityContextImpl```

Shall I create a new issue for this?

**Comment by vpavic** [comment] 2018-09-17 03:16
Please do open a new issue, and provide steps needed to reproduce. Thanks!

**Comment by nagyzsolthun** [comment] 2018-09-17 07:28
Turned out its not an issue. Thanks again for your help.
