### ISSUE TITLE
Take up too much redis connection

### ISSUE THREAD

**Issue by wenjies** [spring-projects/spring-session#1038] opened 2018-04-08 05:12 UTC
A simple request uses so many redis connections. About 20 redis connections, I think there will be performance issues。
The default configuration I use。
E.g ：

@RestController
@RequestMapping("/api")
public class IndexCotroller {
	
 
    @GetMapping("/index")
    public String verifyCode(HttpSession httpSession){
    	httpSession.setAttribute("name","haha");
        return "ok";
    }
     	
    @GetMapping("/get")
    public String get(HttpSession httpSession){
    	return (String) httpSession.getAttribute("name");
    }
}

http://127.0.0.1/api/index

**Comment by eleftherias** [comment] 2021-12-13 12:11
Thanks for reaching out @wenjies. 
I'm going to close this issue as a duplicate of gh-1182.
There is already a discussion and some recommendations in that issue that you may find helpful.

**Closed by eleftherias** 2021-12-13 12:11 UTC
Labels: status: waiting-for-triage
