### ISSUE TITLE
Ability to control the generation of session ids

### ISSUE THREAD

**Issue by artgramlich** [spring-projects/spring-session#201] opened 2015-05-01 03:16 UTC
It would be very nice to have the ability to configure a generator for session ids.  In some older systems, there are (bad) assumptions about the format of session id.

Looking at the code, it seems like it would be fairly simple to add and I would be happy to do the work.

**Comment by rwinch** [comment] 2015-05-01 13:59
Thanks for the report. This appears to be a duplicate of #11 I'm going close this as a duplicate, but if you disagree for some reason feel free to reopen. If you do agree, it would be good to get you to +1 #11 so we can keep track of interest in it.

**Closed by rwinch** 2015-05-01 13:59 UTC
Labels: duplicate
