### ISSUE TITLE
request for a reactive version of org.springframework.session.FindByIndexNameSessionRepository family

### ISSUE THREAD

**Issue by orcloveasagi** [spring-projects/spring-session#1741] opened 2020-12-06 03:50 UTC
**Expected Behavior**
Something like org.springframework.session.FindByIndexNameSessionRepository and its subclasses

**Current Behavior**
We cannot access reactive WebSession by username conveniently.

**Context**
When I tried to build a Spring cloud gateway application,which build on webflux, with spring security and spring session, I found it difficult to implement concurrent session controle sinces there's no reactive implementations for the FindByIndexNameSessionRepository. However I can still accomplish my goals through ReactiveSessionRepository in a more cumbersome way. 
And now I'm going to ask you if you need a more convenient way to access reactive WebSession?
If you do I can package something like FindByIndexNameSessionRepository and make a pr.

**Comment by zkning** [comment] 2021-07-06 01:24
+++

**Comment by chhch** [comment] 2022-09-07 09:54
Duplicate of #914

**Comment by marcusdacoregio** [comment] 2023-07-27 14:54
Closing as duplicate of #914

**Closed by marcusdacoregio** 2023-07-27 14:54 UTC
Labels: type: enhancement, status: waiting-for-triage
