### ISSUE TITLE
Spring session expires after long rest API call despite pinging

### ISSUE THREAD

**Issue by simkentys** [spring-projects/spring-session#1898] opened 2021-08-18 13:12 UTC
I have a spring session timeout set to

    server.servlet.session.timeout = 180

and session is extended every 30 seconds by client pinging server

    @RestController
    public class PingController {
    
      @RequestMapping("/api/ping")
      public void ping(HttpServletRequest request) {}
    }

Problem is that we have a couple of long rest API calls which often can take longer than session timeout to complete, and during that time session expires.

During that long API call, "pinger" is still working, and firing ping requests, however session is not being extended. After long API call is completed the next ping request gets 403.

Is this a bug or an intended functionality?

**Comment by eleftherias** [comment] 2021-08-18 13:43
Thanks for getting in touch, @simkentys, do you have a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?

Is this only an issue when using Spring Session?   
From the code you have shared, it's not clear if the application in question is even using Spring Session.  
The [server.servlet.session.timeout](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.servlet.session.timeout) is not a Spring Session specific property.

**Comment by spring-projects-issues** [comment] 2021-08-25 13:44
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-09-01 13:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-09-01 13:44 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
