### ISSUE TITLE
how to exclude my login request from SessionRepositoryFilter

### ISSUE THREAD

**Issue by kenybao** [spring-projects/spring-session#1502] opened 2019-09-06 03:08 UTC
But I can not find any way to exlude login request ，it seems any request always comes to SessionRepositoryFilter。

**Comment by vpavic** [comment] 2019-09-06 07:42
I'm not sure I understand what's the problem you're facing @kenybao. Could you try and describe the problem in more detail, or even better, provide a minimal sample app that reproduces it?

**Comment by spring-issuemaster** [comment] 2019-09-13 07:44
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-09-20 07:46
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-09-20 07:46 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
