### ISSUE TITLE
Spring Session GemFire incompatible with Spring 5.0

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-session#714] opened 2017-01-17 15:49 UTC
Spring 5 [removed BeanFactoryLocator](https://jira.spring.io/browse/SPR-15154) in https://github.com/spring-projects/spring-framework/commit/ac6aa53031b361e4ea8c74c6bdb4035715f37fb4 and now the [Spring Session GemFire tests](https://jenkins.spring.io/job/spring-session/213/testReport/junit/docs.http/HttpSessionGemFireIndexingITests/findByIndexName/) fail due to the fact that [GemfireBeanFactoryLocator](https://github.com/spring-projects/spring-data-gemfire/blob/f32fc819230f506ba4ff6367dfae26786240bfc9/src/main/java/org/springframework/data/gemfire/GemfireBeanFactoryLocator.java#L52) uses `BeanFactoryLocator `. The stacktrace is

```
...
	Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gemfireCache' defined in docs.http.HttpSessionGemFireIndexingITests$Config: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.data.gemfire.CacheFactoryBean] from ClassLoader [sun.misc.Launcher$AppClassLoader@2a139a55]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:540)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:484)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:249)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:833)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:740)
	... 79 more
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springframework.data.gemfire.CacheFactoryBean] from ClassLoader [sun.misc.Launcher$AppClassLoader@2a139a55]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:652)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:504)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:206)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:187)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:125)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:295)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1005)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
	... 89 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/beans/factory/access/BeanFactoryLocator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:634)
	... 96 more
Caused by: java.lang.ClassNotFoundException: org.springframework.beans.factory.access.BeanFactoryLocator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 112 more
```

**Comment by jxblum** [comment] 2017-01-21 22:24
I just committed [SGF-587](https://jira.spring.io/browse/SGF-587) to the _Spring Data GemFire_ `2.0.x branch that addresses the `GemfireBeanFactoryLocator` issue caused by [SPR-15154](https://jira.spring.io/browse/SPR-15154), which removed the `BeanFactoryLocator` functionality from the core _Spring Framework_.

**Comment by jxblum** [comment] 2017-01-21 22:37
Indeed, the following recent _Spring Session_ [Bamboo CI builds](https://build.spring.io/browse/SESSION) were failing (to **compile**) due to the `NoClassDefFoundError/ClassNotFoundException` caused by the SDG `GemfireBeanFactoryLocator` class implementing the no longer existing core _Spring Framework_ `BeanFactoryLocator` interface...

[Build #31](https://build.spring.io/browse/SESSION-B20X-DEFAULT-31/test/case/222628512)
[Build #32](https://build.spring.io/browse/SESSION-B20X-DEFAULT-32/test/case/222628389)
[Build #33](https://build.spring.io/browse/SESSION-B20X-DEFAULT-33/test/case/222628389)
[Build #34](https://build.spring.io/browse/SESSION-B20X-DEFAULT-34/test/case/222628389)

and...

[Build #35](https://build.spring.io/browse/SESSION-B20X-DEFAULT-35/test/case/222628389)

However, as of [Build #36](https://build.spring.io/browse/SESSION-B20X-36/test), the Spring Session [Bamboo CI build for 2.0.x](https://build.spring.io/browse/SESSION-B20X) is GREEN again.

**Comment by jxblum** [comment] 2017-01-21 22:43
Additionally, [Build #217](https://jenkins.spring.io/job/spring-session/217/testReport/docs.http/HttpSessionGemFireIndexingITests/findByIndexName/) was the last build in the _Spring Session_ [Jenkins CI builds](https://jenkins.spring.io/job/spring-session) to fail because of this problem

The last 2 _Spring Session_ Jenkins CI builds, [Build #218](https://jenkins.spring.io/job/spring-session/218/) and [Build #219](https://jenkins.spring.io/job/spring-session/219/), have **PASSED.**

**Closed** 2017-01-21 22:44 UTC
Labels: build, fixed, GemFire
