### ISSUE TITLE
How to override UUID session generation stategy

### ISSUE THREAD

**Issue by vikas115m** [spring-projects/spring-session#1497] opened 2019-09-02 07:50 UTC
Hi Team,
We are using spring session along with redis (jedis) with spring mvc xml configuration for storing user sessions in redis.

We have more than 20 applications servers for now we are going with default spring session UUID strategy

Is there any chance of UUID /session mix up in case of heavy load?

Also please suggest me a way to override the MAPSESSION class to override the UUID and append some extra counters to make sure that SESSION id is always uniquer per user.
Note: As of now we are using spring session 1.3.5 released session id are always unique.

**Comment by vpavic** [comment] 2019-09-02 19:40
Hi @vikas115m. UUIDs are unique for all practical purposes so you really shouldn't have any issue there.

Regarding custom session id strategy, we have #11 that's tracks that effort so I'm closing this one as duplicate.

**Comment by vpavic** [comment] 2019-09-02 19:40
Duplicate of #11

**Closed by vpavic** 2019-09-02 19:40 UTC
Labels: status: waiting-for-triage
