### ISSUE TITLE
sessions in MapSessionRepository will oom?

### ISSUE THREAD

**Issue by qq756585379** [spring-projects/spring-session#1989] opened 2022-01-04 11:29 UTC
Map<String, Session> sessions in MapSessionRepository may not be deleted?  and than oom?

**Comment by eleftherias** [comment] 2022-01-04 11:38
Thanks for reaching out @qq756585379.  
Please add some additional details and a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue.
At the moment your question is not clear to me.

**Comment by vpavic** [comment] 2022-01-08 17:51
@qq756585379 `MapSessionRepository` generally isn't intended as a production grade solution. If the `Map` supplied doesn't take care of evicting the sessions it could indeed lead to OOM. This is however stated in the `MapSessionRepository` javadoc.

**Comment by spring-projects-issues** [comment] 2022-01-11 11:38
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-01-18 11:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-01-18 11:38 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
