### ISSUE TITLE
Spring Session JDBC JSON format storing is not working

### ISSUE THREAD

**Issue by sivaprasadreddy** [spring-projects/spring-session#2965] opened 2024-05-07 13:55 UTC
**Describe the bug**
I am trying out the **spring-session-sample-boot-jdbc-json-attribute** sample and trying to store an object instead of simple Strings.
Then I am getting the error **LinkedHashMap cannot be cast to MyObject** error.

**To Reproduce**
In the **spring-session-sample-boot-jdbc-json-attribute** sample try to store any custom Object.

I tried customizing the **ObjectMapper** in **SessionConfig.java** as follows:

```
@Bean("springSessionConversionService")
public GenericConversionService springSessionConversionService(ObjectMapper objectMapper) {
		ObjectMapper copy = objectMapper.copy();
                 //Added following 3 lines
		copy.enable(JsonGenerator.Feature.IGNORE_UNKNOWN);
		copy.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
		copy.activateDefaultTyping(copy.getPolymorphicTypeValidator(), ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);

		GenericConversionService converter = new GenericConversionService();
		converter.addConverter(Object.class, byte[].class, new SerializingConverter(new JsonSerializer(copy)));
		converter.addConverter(byte[].class, Object.class, new DeserializingConverter(new JsonDeserializer(copy)));
		return converter;
}
```

Then while storing the object in session, it is throwing the following error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: column "attribute_bytes" is of type jsonb but expression is of type bytea
  Hint: You will need to rewrite or cast the expression.
  Position: 56
```

But, in SessionConfig.java we have already customized the query to cast to jsonb type as follows:

```
private static final String CREATE_SESSION_ATTRIBUTE_QUERY = """
			INSERT INTO %TABLE_NAME%_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES)
			VALUES (?, ?, encode(?, 'escape')::jsonb)
			""";
```

Any pointers to fix this issue?

**Comment by marcusdacoregio** [comment] 2024-05-07 13:58
Hello, @sivaprasadreddy. Have you tried the steps described in https://docs.spring.io/spring-session/reference/configuration/jdbc.html#session-attributes-as-json?

Can you provide a minimal, reproducible sample so I can make sure I'm not missing anything when debugging it?

**Comment by marcusdacoregio** [comment] 2024-05-08 13:35
Hi @sivaprasadreddy, thanks for the reproducer. The error was caused because only the create session attribute query has been customized to consider the attribute value as JSON, you also need to customize the update session attribute query, like so:

```java
private static final String CREATE_SESSION_ATTRIBUTE_QUERY = """
		INSERT INTO %TABLE_NAME%_ATTRIBUTES (SESSION_PRIMARY_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES)
		VALUES (?, ?, encode(?, 'escape')::jsonb)
		""";

private static final String UPDATE_SESSION_ATTRIBUTE_QUERY = """
		UPDATE %TABLE_NAME%_ATTRIBUTES
		SET ATTRIBUTE_BYTES = encode(?, 'escape')::jsonb
		WHERE SESSION_PRIMARY_ID = ?
		AND ATTRIBUTE_NAME = ?
		""";

@Bean
SessionRepositoryCustomizer<JdbcIndexedSessionRepository> customizer() {
	return (sessionRepository) -> {
		sessionRepository.setCreateSessionAttributeQuery(CREATE_SESSION_ATTRIBUTE_QUERY);
		sessionRepository.setUpdateSessionAttributeQuery(UPDATE_SESSION_ATTRIBUTE_QUERY);
	};
}
```

I see that there is no mention about that in the docs, are you interested in submitting a PR that includes that information? If not, I'm happy to take it.

**Comment by sivaprasadreddy** [comment] 2024-05-08 15:02
@marcusdacoregio I will create a PR.

**Comment by marcusdacoregio** [comment] 2024-05-08 15:06
Thank you. Please target the 3.1.x branch since it is the latest supported version

**Comment by sivaprasadreddy** [comment] 2024-05-08 16:13
@marcusdacoregio When using Spring Security the default typing is activated by configuring `copy.registerModules(SecurityJackson2Modules.getModules(this.classLoader));`.

If not, we need to explicitly enable it using `copy.activateDefaultTyping(copy.getPolymorphicTypeValidator(), ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);`.

**Comment by marcusdacoregio** [comment] 2024-05-08 17:35
Hi @sivaprasadreddy, that is expected. You have to tell Jackson how to deserialize the JSON into your expected type, you can do that by activating the default typing, using `@JsonTypeInfo` annotation in your classes or creating a mixin.

**Comment by marcusdacoregio** [comment] 2024-05-08 17:36
Closing in favor of https://github.com/spring-projects/spring-session/pull/2966

**Closed by marcusdacoregio** 2024-05-08 17:36 UTC
Labels: type: bug, in: jdbc
