### ISSUE TITLE
Crazy bug with change of session parameter "_s"

### ISSUE THREAD

**Issue by mayras** [spring-projects/spring-session#958] opened 2017-12-29 10:18 UTC
SessionRepositoryRequestWrapper.commitSession (line 236):

			HttpSessionWrapper wrappedSession = getCurrentSession();

For example, my previous requests was with _s=1, then I decided to get some CSS file using _s=0 (using another session), above method will returns HttpSessionWrapper for _s=1 but must for _s=0, why? because application doesn't call SessionRepositoryRequestWrapper.setCurrentSession for new parameter _s=0. It's really impossible to switch b/w sessions.

**Comment by vpavic** [comment] 2018-01-04 13:30
Thanks for the report @mayras. From the information you've provided it's not clear what your actual use case is. Could you provide a sample application that could be used to reproduce the issue?

**Comment by vpavic** [comment] 2018-11-12 22:35
Closing due to lack of feedback. Please comment back if you can provide more details and we can re-open the issue.

Additionally, this appears to be the duplicate of #957.

**Comment by vpavic** [comment] 2018-11-12 22:35
Duplicate of #957

**Closed by vpavic** 2018-11-12 22:35 UTC
Labels: waiting for feedback
