### ISSUE TITLE
Autowiring of session scoped beans after deserialization

### ISSUE THREAD

**Issue by usharik** [spring-projects/spring-session#1551] opened 2019-11-28 13:47 UTC
I use `spring-session-data-redis 2.2.0.RELEASE` in the Spring Boot application.

I have Session scoped bean with one autowired field with singleton scoped bean, like in code example.
```
@Service
@Scope(scopeName = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
public class CartServiceImpl implements Serializable {
 
      private transient ProductService productService;
 
      @Autowired
      public CartService(ProductService productService) {
            this.productService = productService;
      }
 
}
 
public interface ProductService {
    // some methods
}
 
@Service
public class ProductServiceImpl implements ProductService {
    // some logic
}
```

The `productService` is not autowired back after the bean was restored from Redis session storage. The pretty same behaviour is with setter ingestion.

I suggest this behaviour is not correct or at least not straight forward and could be reported as a bug.

**Comment by usharik** [comment] 2019-11-28 13:52
There are two workarounds I found:
1. `proxyMode = ScopedProxyMode.TARGET_CLASS` for autowired singleton bean. It works but only until application restarts. All sessions in Redis from previous application instance will cause ClassNotFound exception. Also, it's not working for Jackson serialization
2. Manual autowiring with obtaining of current application context in `readObject` method or `@JsonCreator` annotated constructor. That works but not looks like a good practics code.

**Comment by rmueller83** [comment] 2022-01-10 17:06
@usharik do you have an example of how to implement the `readObject` method for your above code?
And did you find another solution in the meantime?
It is a bit sad that none of the Spring developers commented on this issue.

**Comment by usharik** [comment] 2022-01-10 17:09
Yes, it sad. I suppose only proper way to act here is not to use autowiring in session scoped beans if we use any kind of session serialization.

**Comment by ovshevchuk** [comment] 2023-12-28 13:38
@usharik faced the same issue. Added scope "session" bean to "cache" user information that I get from DB.
Originally it worked fine because our application immediately redirects to login page. Hence - first call to session bean got user info from DB and didn't need to use autowired UserService anymore. So deserialization not autowiring UserService bean had no effect.

However, when we added support for "GUEST" users things got more complicated.
It appears that if you call such bean with guest user - Spring already creates a session and returns you a session cookie.
Then, if you login, instead of creating a new session - it updates existing session, thus same "session"-bean that was used for providing user information for guest user is used to provide info for logged in user. As a consequence - user info is incorrect and I can`t update it because by that time - autowired UserService is already null.

**Comment by marcusdacoregio** [comment] 2023-12-29 14:09
Hi folks, is anyone able to provide a minimal, reproducible sample to help us debug this issue?

**Comment by ovshevchuk** [comment] 2023-12-29 14:14
I think I will be able to provide it after New Year holidays.

**Comment by ovshevchuk** [comment] 2024-01-02 14:21
[session-bean-poc.zip](https://github.com/spring-projects/spring-session/files/13810790/session-bean-poc.zip)
Here a quick and dirty POC to reproduce this.
It requires local Redis so docker-compose.yml included.
After starting the application go to localhost:8080 and press "Test Value". You should see value = 42 and "Autowired Bean is NULL" = false.
If you return to home page and try "Test Value" again - you will see "Autowired Bean is NULL" = true.
In itself it is not a problem for me. However, the real problem is - if you go to home page, click login, enter "user"/"password" you will again see "Autowired Bean is NULL" = true.
This is because, for some reason, user after login is treated as having the same session as guest user few moments prior for the purposes of SCOPE_SESSION bean.
Combination of this and not re-autowiring services after deserialization makes SCOPE_SESSION bean approach unusable.

I am really stuck here because (for my purposes) I can't cache user information when SCOPE_SESSION bean is created - because it is created when user is still an unauthorized guest. And when user does get authorized - I no longer have access to autowired services to retrieve fresh user information.

I am also open to any workarounds anyone could came up with.

**Comment by marcusdacoregio** [comment] 2024-01-17 13:22
Hi, @usharik. Thank you very much for the reproducible sample, it helped a lot.

If we take a look at [the documentation](https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-other) about bean scopes, it seems to me that the behavior is consistent with what is described there. Since Spring Session does not know whether an authentication happened, a workaround would be to tell Spring Security to create a new session when an authentication happens and do not copy the attributes from the old session, see [the related documentation](https://docs.spring.io/spring-security/reference/servlet/authentication/session-management.html#_configuring_session_fixation_protection). By not copying the attributes that are not related to Spring Security, it won't copy your serialized session scoped bean, therefore it will have to be instantiated again and its dependencies injected.

```java
http
    // ...
    .sessionManagement((sessions) -> sessions
        .sessionFixation((fixation) -> fixation.newSession())
    )
```

I'll look into the behavior with `transient` fields being different when using Spring Session.

**Comment by marcusdacoregio** [comment] 2024-01-17 14:08
@usharik, to retain a reference to a singleton bean after deserialization, you can change your code to use `ObjectProvider<ProductService>` in the injection point and use it to retrieve the current instance on demand every time it is needed, as described in [the Scoped Beans as Dependencies section](https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html#beans-factory-scopes-other-injection) of the docs.

It would look something like:

```java
@Service
@Scope(scopeName = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
public class CartServiceImpl implements Serializable {
 
      private ObjectProvider<ProductService> productService;
 
      @Autowired
      public CartService(ObjectProvider<ProductService> productService) {
            this.productService = productService;
      }

      public void getProducts() {
          this.productService.getIfAvailable().getProducts();
      }
 
}
```

Since the behavior is expected and described in the documentation about bean scopes I will close this as solved.

**Closed by marcusdacoregio** 2024-01-17 14:08 UTC
Labels: type: bug

**Comment by ovshevchuk** [comment] 2024-01-25 16:43
Hi @marcusdacoregio , It was I who provided a simple POC.
I`ve tested your suggestions and both things worked for POC.

However, in our real-world project first solution doesn`t work. It doesn`t work because we also use Keycloak Spring Boot Adapter and, after quick search, it looks like it is a known issue that Session Fixation configuration has no effect for that. 
That has nothing to do with original issue, obviously, and since the 2nd solution works like a charm - You have my greatest thanks.
