### ISSUE TITLE
RedisIndexedSessionRepository::deleteById should be safe

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-session#1991] opened 2022-01-10 02:38 UTC
**Describe the bug**
I'm trying to fix https://github.com/spring-projects/spring-session/issues/1939 by intercept `SessionRepository::findById`,
`RedisIndexedSessionRepository::deleteById` will throw SerializationFailedException, but other `SessionRepository` implementations  is safe.

```java
	@Around("execution(public * findById(String)) and target(sessionRepository)")
	public Object intercept(ProceedingJoinPoint pjp, SessionRepository<?> sessionRepository) throws Throwable {
		try {
			return pjp.proceed();
		}
		catch (RuntimeException ex) {
			if (ex instanceof SerializationFailedException || ex.getCause() instanceof SerializationFailedException) {
				sessionRepository.deleteById((String) pjp.getArgs()[0]); // will throw SerializationFailedException
				return null;
			}
			throw ex;
		}
	}
```

**To Reproduce**
tamper hash value in redis key `spring:session:sessions:{id}`, let `RedisIndexedSessionRepository::findById` will throw SerializationFailedException.

**Expected behavior**
`RedisIndexedSessionRepository::deleteById` will clear data as possible and do NOT throw exception.

**Comment by quaff** [comment] 2022-01-10 02:50
See https://github.com/spring-projects/spring-session/pull/646#issuecomment-287350936

**Comment by eleftherias** [comment] 2022-01-11 08:59
Hi @quaff, this is a duplicate of #529.
The current implementation of `RedisIndexedSessionRepository` requires the entire session to be retrieved in order to clean up the values properly.
That's what causes the Exception if the stored session is damaged.
There is some discussion in #529 which may be helpful.
Additionally it is worth trying to figure out why the session gets into a state where it cannot be deserialized and try to fix the root of the problem.

**Closed by eleftherias** 2022-01-11 08:59 UTC
Labels: type: bug, status: waiting-for-triage

**Comment by quaff** [comment] 2022-01-12 00:53
> Additionally it is worth trying to figure out why the session gets into a state where it cannot be deserialized and try to fix the root of the problem.

@eleftherias Upgrade spring-security will cause deserialization failure.
