### ISSUE TITLE
Exceptions in JdbcOperationsSessionRepository.save()

### ISSUE THREAD

**Issue by virtualdogbert** [spring-projects/spring-session#687] opened 2016-12-07 14:52 UTC
So I've been having these huge hard to track down stack traces eating through my logs and I think I've tracked them down to if an exception is thrown within the save function of the JdbcOperationsSessionRepository(I have a slightly altered version for audit logging). What are you thoughts about if within the JdbcOperationsSessionRepository I wrapped the save method in a try catch and just logged the exception there? Could this cause other issues? The save method doesn't currently have a throws in its signature.

One of the causes that I saw in the logs was that there was a foreign key validation trying to update a property(partial stack trace bellow). I'm not sure if this is the only cause, because before deleting all the current sessions from the database, we had catalina.out at over 20GB. After deleting the sessions it's calmed down and for the past day and a half we're at 300MB. 

Another thought could this be related to the cleanUpExpiredSessions cron job, maybe tweaking that might help one of the causes?

I saw a similar issue when we upgraded our framework(Grails 3), in dev, where it could no longer  decode some attributes, but clearing the sessions fixes that issue.

```
2016-11-29 16:54:48,449 [http-nio-149.65.64.21-9080-exec-91] ERROR org.springframework.boot.context.web.ErrorPageFilter forwardToErrorPage | Forwarding to error page from request [/app/getRootNode] due to exception [PreparedStatementCallback; SQL [INSERT INTO SPRING_SESSION_ATTRIBUTES(SESSION_ID, ATTRIBUTE_NAME, ATTRIBUTE_BYTES) VALUES (?, ?, ?)]; Cannot add or update a child row: a foreign key constraint fails (`portaldb`.`SPRING_SESSION_ATTRIBUTES`, CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `SPRING_SESSION` (`SESSION_ID`) ON DELETE CASCADE); nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`portaldb`.`SPRING_SESSION_ATTRIBUTES`, CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK` FOREIGN KEY (`SESSION_ID`) REFERENCES `SPRING_SESSION` (`SESSION_ID`) ON DELETE CASCADE)]
at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243) ~[spring-jdbc-4.1.8.RELEASE.jar:4.1.8.RELEASE]
at org.springfr
...
```

**Comment by rwinch** [comment] 2016-12-07 19:53
> What are you thoughts about if within the JdbcOperationsSessionRepository I wrapped the save method in a try catch and just logged the exception there? Could this cause other issues? The save method doesn't currently have a throws in its signature.

I would not try catch it as this would mask the underlying issue. We should try to fix the root cause.

> After deleting the sessions it's calmed down and for the past day and a half we're at 300MB.

Are you seeing more exceptions?

> Another thought could this be related to the cleanUpExpiredSessions cron job, maybe tweaking that might help one of the causes?

There have been some issues reported on the cleanupExpiredSessions job. What version of Spring Session are you using? What database are you using?

cc @jkubrynski

**Comment by jkubrynski** [comment] 2016-12-07 19:58
@rwinch I think you wanted to add @vpavic :)

**Comment by virtualdogbert** [comment] 2016-12-07 20:40
> I would not try catch it as this would mask the underlying issue. We should try to fix the root cause.

Absolutely, I was only thinking about using a try/catch, as a stop gap, until we could get a proper solution, although the exceptions at least for now have died down. Although should there be a try/catch with proper logging in that method, because it seem like any exception thrown from there can get lost is a sea of stack traces from it?

> Are you seeing more exceptions?

Not at the moment.

> There have been some issues reported on the cleanupExpiredSessions job. What version of Spring >Session are you using? What database are you using?

compile 'org.springframework.session:spring-session:1.2.0.RELEASE'
MySQL 5.1.73

The reason I chose JDBC over redis, specifically was because I didn't need to get IT involved, and because I don't have sudo on my  own box.

**Comment by vpavic** [comment] 2016-12-07 21:08
@virtualdogbert Could you share the _slightly altered version_ of `JdbcOperationsSessionRepository` you're referring to?

The foreign key constraint error seems to indicate there was an attempt to write an attribute for a session id that didn't exist any more. More context would be useful - was your app under heavy load when these exception occurred?

> Another thought could this be related to the cleanUpExpiredSessions cron job, maybe tweaking that might help one of the causes?

Can you clarify this a bit more? Did you experience any particular problem with the execution of this method?

> I saw a similar issue when we upgraded our framework(Grails 3), in dev, where it could no longer decode some attributes, but clearing the sessions fixes that issue.

This would suggest that the upgrade of your framework changed versions of classes saved in the session, therefore making the session unable to deserialize.

BTW could you upgrade to `1.2.2.RELEASE` and see if that helps?

**Comment by virtualdogbert** [comment] 2016-12-13 22:42
Sharing the altered version would require approval from my boss, which maybe possible, but I don't think it's going to be worth it. The changes I made, was I converted it to groovy, so I could extend a Grails trait, to call events for audit logging.

Strangely enough this issue has completely disappeared, for now... My thought is that the app was under a particular load and that cleanUpExpiredSessions killed some sessions, as they they were about to be updated. So what might be a better solution is to check to see if the session exists, in the transaction, before doing the update, and just returning if it doesn't. That would avoid the spewing of errors and crewing up of logs.

In retrospect it would have probably been better to do a feature request for events, relating to log in/out and session timeout, with the principal id/username, but then to do a temp fix for this issue I would be back to messing with the JdbcOperationsSessionRepository, a least until you had an update, that prevented the issue.

I will try to do the update in the somewhat near future.
Thanks

**Comment by virtualdogbert** [comment] 2016-12-20 20:14
@vpavic   I just tried 1.2.2 and that causes a lengthy exception ending in:
Caused by: java.io.InvalidClassException: org.springframework.security.core.context.SecurityContextImpl; local class incompatible: stream classdesc serialVersionUID = 410, local class serialVersionUID = 400

**Comment by vpavic** [comment] 2016-12-20 20:30
That sounds like you have a session in your data store that contains authentication issued by Spring Security 4.0 (`serialVersionUID = 400L`) while your app currently uses Spring Security 4.1 (`serialVersionUID = 410L`) hence the `InvalidClassException` exception.

Try flushing your session store and trying again or dropping Spring Security back to 4.0.

**Comment by virtualdogbert** [comment] 2016-12-20 21:22
Facepalm duh, just killed all the session and it seems fine. Although that's strange, we didn't update our spring security.

**Comment by vpavic** [comment] 2017-01-07 08:16
Closing due to unable to reproduce. If you encounter the problem again, please update with more details and re-open the issue.

**Closed by vpavic** 2017-01-07 08:16 UTC
Labels: question
