### ISSUE TITLE
Hazelcast Store throws exception if used with Standalone Hazelcast instance

### ISSUE THREAD

**Issue by philnate** [spring-projects/spring-session#1055] opened 2018-04-16 12:32 UTC
With the improvements made in #850/#983 to the hazelcast backend, Hazelcast if ran as a Standalone service requires now the spring-session jar in it's class path. Otherwise the application is completely inaccessible, throwing this exception during access:

```
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: org.springframework.session.hazelcast.HazelcastSessionRepository$SessionUpdateEntryProcessor
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.map.MapExecuteOnKeyMessageTask.prepareOperation(MapExecuteOnKeyMessageTask.java:42) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:62) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) ~[hazelcast-3.8.9.jar:3.8.9]
	at ------ submitted from ------.(Unknown Source) ~[?:?]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95) ~[hazelcast-client-3.8.9.jar:3.8.9]
	at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:32) ~[hazelcast-client-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:155) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.spi.ClientProxy.invokeOnPartition(ClientProxy.java:171) ~[hazelcast-client-3.8.9.jar:3.8.9]
	at com.hazelcast.client.spi.ClientProxy.invoke(ClientProxy.java:165) ~[hazelcast-client-3.8.9.jar:3.8.9]
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnKeyInternal(ClientMapProxy.java:1255) ~[hazelcast-client-3.8.9.jar:3.8.9]
	at com.hazelcast.client.proxy.ClientMapProxy.executeOnKey(ClientMapProxy.java:1249) ~[hazelcast-client-3.8.9.jar:3.8.9]
	at org.springframework.session.hazelcast.HazelcastSessionRepository.save(HazelcastSessionRepository.java:209) ~[spring-session-1.3.2.RELEASE.jar:?]
	at org.springframework.session.hazelcast.HazelcastSessionRepository.save(HazelcastSessionRepository.java:111) ~[spring-session-1.3.2.RELEASE.jar:?]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:245) ~[spring-session-1.3.2.RELEASE.jar:?]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:217) ~[spring-session-1.3.2.RELEASE.jar:?]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:170) ~[spring-session-1.3.2.RELEASE.jar:?]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80) ~[spring-session-1.3.2.RELEASE.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) ~[spring-boot-actuator-1.5.12.RELEASE.jar:1.5.12.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.16.RELEASE.jar:4.3.16.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.29.jar:8.5.29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.ClassNotFoundException: org.springframework.session.hazelcast.HazelcastSessionRepository$SessionUpdateEntryProcessor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_162]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_162]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
	at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:149) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:123) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:522) ~[hazelcast-3.8.9.jar:3.8.9]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1859) ~[?:1.8.0_162]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1745) ~[?:1.8.0_162]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2033) ~[?:1.8.0_162]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567) ~[?:1.8.0_162]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427) ~[?:1.8.0_162]
	at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:48) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:184) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.map.MapExecuteOnKeyMessageTask.prepareOperation(MapExecuteOnKeyMessageTask.java:42) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.AbstractPartitionMessageTask.processMessage(AbstractPartitionMessageTask.java:62) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.initializeAndProcessMessage(AbstractMessageTask.java:123) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.run(AbstractMessageTask.java:103) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:142) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125) ~[hazelcast-3.8.9.jar:3.8.9]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:100) ~[hazelcast-3.8.9.jar:3.8.9]
```

See http://docs.hazelcast.org/docs/latest-development/manual/html/Distributed_Computing/Entry_Processor/Performing_Fast_In-Memory_Map_Operations.html:

> Usually you perform a loop of keys-- executing IMap.get(key), mutating the value, and finally putting the entry back in the map using IMap.put(key,value)
> If you perform this process from a client or from a member where the keys do not exist, you effectively perform two network hops for each update: the first to retrieve the data and the second to update the mutated value.
>
> If you are doing the process described above, you should consider using entry processors. An entry processor executes a read and updates upon the member where the data resides. This eliminates the costly network hops described above.

I'm not sure if the Hazelcast server should have a hard dependency of spring-session. It might not always be possible to put those jars into the Hazelcast cluster (updates might become harder as well). If this is the way going forward, then at least the documentation needs to be updated to reflect this requirement for Standalone Hazelcast Clusters.

**Comment by vpavic** [comment] 2018-04-16 13:12
Thanks for the report @philnate. Actually this requirement is present for some time now, since we provided Hazelcast implementation of `FindByIndexNameSessionRepository` which requires registration of `PrincipalNameExtractor` with Hazelcast server. Of course, if you're not using `FindByIndexNameSessionRepository#findByIndexNameAndIndexValue` then perhaps this requirement didn't apply to your use case.

We also have some documentation on this (see [here](https://docs.spring.io/spring-session/docs/current/reference/html5/#security-spring-configuration) and [here](https://docs.spring.io/spring-session/docs/current/reference/html5/#api-enablehazelcasthttpsession-storage)), which should suggest the present of Spring Session classes is required in client-server topology.

Having said that, I agree that ideally we shouldn't require this, and we could use this ticket to track the progress of improving the current situation.

**Comment by philnate** [comment] 2018-04-16 15:26
@vpavic thank you for the fast reply. Thanks for pointing me to the documentation, one of the links I didn't see before. Still I would say that it's not getting overly clear that some server side registration is needed. 
Maybe this [place](https://docs.spring.io/spring-session/docs/current/reference/html5/#security-spring-configuration) would the best to make this requirement clear. The reference to Hazelcast documentation alone doesn't implies to me that for Standalone setup some classpath addition to Hazelcast is needed.

**Comment by vpavic** [comment] 2018-06-13 17:27
@philnate We've got two issues that will cover concerns you express here:

- #1012 for improving documentation
- #1101 for improving support for client-server topology

To reduce the amount of opened issues on the same topic, I'm going to close this one as duplicate. Please track the two issues listed above.

**Comment by vpavic** [comment] 2018-06-13 17:28
Duplicate of #1012

**Closed by vpavic** 2018-06-13 17:28 UTC

**Comment by vpavic** [comment] 2018-07-17 20:15
@philnate The situation will be improved in `2.0.5.RELEASE` with #1012 resolved, see [this comment](https://github.com/spring-projects/spring-session/issues/1101#issuecomment-405708178) for details.
