### ISSUE TITLE
Hazelcast ClientConfig with spring-session

### ISSUE THREAD

**Issue by fplini** [spring-projects/spring-session#1068] opened 2018-05-08 17:19 UTC
Hi all,
I have some webapp that uses hazelcast to store the user session.
I followed this guide https://docs.spring.io/spring-session/docs/current/reference/html5/guides/java-hazelcast.html#security-spring-configuration
but here there is only the configuration for the embedded instance and not for remote (standalone) instance (ClientConfig).

How can I do that?

Thanks 
Fabrizio

**Comment by vpavic** [comment] 2018-06-13 17:37
Hi @fplini, sorry for the late response.

We've got two issues that will cover concerns you expressed here:

- #1012 for improving documentation
- #1101 for improving support for client-server topology

To reduce the amount of opened issues on the same topic, I'm going to close this one as duplicate. Please track the two issues listed above.

Having said that, with client-server topology, you should ensure that your Hazelcast server is configured as explained in the part of our reference manual that [you linked to](https://docs.spring.io/spring-session/docs/current/reference/html5/guides/java-hazelcast.html#security-spring-configuration). You also need to ensure that Spring Session classes are present on the classpath (see #1101 for more details). As for the client part, it should be simple and you can use something like we do in our integration tests:

https://github.com/spring-projects/spring-session/blob/63a215f73bcc9440860d7b9381dbc753888824ab/spring-session-hazelcast/src/integration-test/java/org/springframework/session/hazelcast/HazelcastClientRepositoryITests.java#L63-L74

Also see #1055.

**Comment by vpavic** [comment] 2018-06-13 17:37
Duplicate of #1012

**Closed by vpavic** 2018-06-13 17:37 UTC
