### ISSUE TITLE
using secondary data source  for my spring session app

### ISSUE THREAD

**Issue by eshiett1995** [spring-projects/spring-session#858] opened 2017-08-19 23:22 UTC
i am using Spring boot with Spring session Jdbc,  i want to use h2, and already have an existing PostgreSQL data-source in my properties file. but as much as i try to configure my session to use h2 for storing session. it still tries to use PostgreSQL.  please is there anything i can do?

**Comment by vpavic** [comment] 2017-08-20 16:59
Duplicate of #828.

**Closed by vpavic** 2017-08-20 16:59 UTC
