### ISSUE TITLE
spring webfux use spring session when session.getAttributes().remove("key")  then  "key" is not remove the "key" value is null   

### ISSUE THREAD

**Issue by ghghhh** [spring-projects/spring-session#1062] opened 2018-04-27 16:13 UTC
spring webfux use spring session when session.getAttributes().remove("key")  then  "key" is not remove and the key's value is null.
it has an bug in getSession method on 

        @Override
	public Mono<RedisSession> findById(String id) {
		String sessionKey = getSessionKey(id);
		return this.sessionRedisOperations.opsForHash().entries(sessionKey)
				.collect(
						Collectors.toMap(e -> e.getKey().toString(), Map.Entry::getValue))    --some value is null and throw new NullPointerException()
				.filter(map -> !map.isEmpty()).map(new SessionMapper(id))
				.filter(session -> !session.isExpired()).map(RedisSession::new)
				.switchIfEmpty(Mono.defer(() -> deleteById(id).then(Mono.empty())));
	}

**Comment by vpavic** [comment] 2018-04-27 20:09
Thanks for the report @ghghhh. This has been resolved in #1035 and will be a part of `2.0.3.RELEASE`.

Duplicate of #1035

**Closed by vpavic** 2018-04-27 20:09 UTC
