### ISSUE TITLE
spring-session-hazelcast Compatibility with hazelcast:4.0.1

### ISSUE THREAD

**Issue by adeniyiodunlami** [spring-projects/spring-session#1644] opened 2020-06-03 00:21 UTC
Compatibility with Hazelcast:4.0.1

Many changes have been introduced into the Hazelcast:4.0.1 API and there are compatibility
issues with the latest spring-session-hazelcast implementation.

This means that we cannot use spring-session-hazelcast with the latest Hazelcast:4.0.1 release which is needed to run on AWS ECS/Fargate infrastructure.

**Comment by eleftherias** [comment] 2020-06-04 16:21
Thanks for bringing this up @adeniyiodunlami and to everyone that has upvoted it.

This issue has been raised before, in gh-1584.
Please refer to the discussion there and upvote that issue instead.

Regarding your comment about 
> the latest Hazelcast:4.0.1 release which is needed to run on AWS ECS/Fargate infrastructure.

Could you please share any resources where this is documented?

I will close this as a duplicate of gh-1584, feel free to add any additional comments to that issue.

**Closed by eleftherias** 2020-06-04 16:21 UTC
Labels: status: waiting-for-triage, type: enhancement

**Comment by adeniyiodunlami** [comment] 2020-06-04 16:44
Thanks for attending to this and pointing me to the previously raised issue.

On the compatibility issue, a few details are stated in the version compatibility section here
https://github.com/hazelcast/hazelcast-aws/blob/master/README.md
"hazelcast-aws 3+ is compatible with hazelcast 4+"

Hazelcast-aws support for Fargate is available in hazelcast-aws:3.2. I will be glad if there is a work around that you can point me to. 

Again, I know I may be thinking too (much) aloud, can a "hazelcast:4.0.1 compatible version" be released in spring-session:2.3.1 or spring-session:2.3.1.x ?

**Comment by eleftherias** [comment] 2020-06-08 20:34
Thank you for sharing that documentation.
Knowing that AWS Fargate requires Hazelcast 4 will help up prioritize support for it.

We are looking at creating a Hazelcast 4 compatible version in Spring Session 2.4.
This means we would still use Hazelcast 3, but a user would be able to override the version to Hazelcast 4 without getting errors.

**Comment by adeniyiodunlami** [comment] 2020-06-09 18:06
Thank you for confirming this. We are glad to hear that you have decided to prioritize this enhancement in the next release.
