### ISSUE TITLE
Support heterogeneous spring session version in client / server topology

### ISSUE THREAD

**Issue by dougkei** [spring-projects/spring-session#1312] opened 2019-01-14 08:53 UTC
Suggest to customized serialization of SessionUpdateEntryProcessor such that single hazelcast server cluster can serve clients of different spring session versions (e.g. 1.3.5, 2.0.8 and 2.1.3) concurrently.
Suggested approaches:
- SessionUpdateEntryProcessor to implement Portable
- build StreamSerializer for SessionUpdateEntryProcessor
- SessionUpdateEntryProcessor to provide public getter/setter methods so consumer can build their own serialization mechanism as above

**Comment by vpavic** [comment] 2019-01-15 19:30
Thanks for the suggestion @dougkei - we already have #1131 to handle some serialization related improvements. Can you add your comments over there? I think we even might consider this one as duplicate since all those improvements could be implemented together..

**Comment by veereshwaran** [comment] 2019-01-16 11:43
Hi @vpavic 
I have uploaded sample application to reproduce this issue 

Can you refer below git repo?
https://github.com/veereshwaran/client-applucation 

On html page I am calling two API's to SSO server
1. /user/whoami
2. /user

If I set spring.session.store-type=none
200 Ok Status received for above two API calls
 
So, My client application properly renders the user-details properly

If I set spring.session.store-type=redis
First API ("/whoami") gives 200 OK status


Second API ("/user") gives 500 Error with following error message
`
{
	"timestamp": "2019-01-16T11:41:33.357+0000",
	"status": 500,
	"error": "Internal Server Error",
	"message": "Error in execution; nested exception is io.lettuce.core.RedisCommandExecutionException: ERR no such key",
	"path": "/user"
}
`
So my application not rendering user-detail

**Comment by veereshwaran** [comment] 2019-01-16 11:55
I think following code block may cause this issue
https://github.com/spring-projects/spring-session/blob/f00a1b9c6fce90957387d9793bd517ed8b808c3b/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L826

In previous version 1.3

https://github.com/spring-projects/spring-session/blob/3db2e13d7ed0e152d6068dfebf6575a059556dfc/spring-session/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L764-L769

Here It will keep the previous session

I have configured HttpSecurity
http..sessionManagement().sessionFixation().none();

But it is not working.

**Comment by vpavic** [comment] 2019-01-16 11:57
@veereshwaran Thanks for the details - however shouldn't these comments go in #1311?

**Comment by veereshwaran** [comment] 2019-01-16 11:58
Yes by mistake I posted here

**Comment by vpavic** [comment] 2019-01-28 15:37
I'm going to close this one as duplicate of #1131.

**Comment by vpavic** [comment] 2019-01-28 15:38
Duplicate of #1131

**Closed by vpavic** 2019-01-28 15:37 UTC
Labels: waiting for feedback
