### ISSUE TITLE
Spring Session start to connect to redis even @EnableRedisHttpSession not added

### ISSUE THREAD

**Issue by xfcjscn** [spring-projects/spring-session#332] opened 2016-01-06 00:30 UTC
Spring Session start to connect to redis even @EnableRedisHttpSession not added. In this case, it's not possible to disable Spring Session in different test enveroment. Is it possible to have an enhance here?

**Comment by shakuzen** [comment] 2016-01-06 02:03
@xfcjscn Are you using Spring Boot 1.3 or later? If you are, auto-configuration was added for Spring Session with Redis in 1.3 and will be activated when Spring Session and Redis are on the classpath. See [the corresponding documentation](http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-session.html) and [SessionAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/session/SessionAutoConfiguration.java).

I don't currently see a way to disable it if you have Spring Session and Redis on your classpath but don't want it auto-configured. If an option to disable it is what you would like to see, it would be an enhancement request to Spring Boot. You can open a ticket in [their issue tracker](https://github.com/spring-projects/spring-boot/issues).

If you are not using Spring Boot, then please provide more details about your setup.

**Comment by xfcjscn** [comment] 2016-01-06 02:31
I am using spring boot 1.3.1.
After I checked the source code I found that:
Bean of RedisHttpSessionConfiguration register an EnableRedisKeyspaceNotificationsInitializer bean which will create RedisConnection after property setted. This means only if you put spring session as dependency into your classpath, and bean auto scan enabled, RedisConnection will automatically created, and can not be explicitly controlled.

**Comment by fedecz** [comment] 2016-01-12 00:11
I'm seeing the same issue. As soon as the redis dependencies are in the classpath, the Spring boot will try to create a connection to Redis. This might now always be the case. Even though I have Redis in the classpath, I'd like to turn it on only in specific environments. Adding a @ConditionalOnProperty to the configurer would be ideal since we can enable/disable Redis Sessions with only a config change and not deal with the classpath change

**Comment by fedecz** [comment] 2016-01-12 00:22
another question, if Redis is being loaded up whenever spring finds it in the classpath, what's the purpose of @EnableRedisHttpSession ? what does it do then? Thanks

**Comment by youlib** [comment] 2016-01-19 12:17
I'm facing the same issue, even with the entire redis session config commented out, it still tries to instantiate bean 'enableRedisKeyspaceNotificationsInitializer', so testing becomes an issue. Any ideas?

**Comment by shakuzen** [comment] 2016-01-19 15:23
@fedecz The `@EnableRedisHttpSession` is a Spring Session annotation that can be used without Spring Boot. Spring Boot internally uses that annotation as part of its auto-configuration.

If you want to be able to control the auto-configuration via a property, I believe it would be an enhancement request in Spring Boot. It will possibly be covered as part of spring-projects/spring-boot#4508. However, since it encompasses more than a simple on/off switch and requires Spring Session 1.1, the earliest it would be considered is Spring Boot 1.4, I imagine.

If you want an enabled/disabled property sooner than that, please make your case to the Spring Boot team on their issue tracker. I do not think there is anything to be done in the Spring Session project itself for your enhancement request as the behavior is specific to Spring Boot.

**All:**
Have you tried excluding the `SessionAutoConfiguration` in your application? Like the following if you are using the `@SpringBootApplication` annotation.

```java
@SpringBootApplication(exclude = SessionAutoConfiguration.class)
```

Or likewise for `@EnableAutoConfiguration`:

```java
@EnableAutoConfiguration(exclude = SessionAutoConfiguration.class)
```

**Comment by youlib** [comment] 2016-01-20 10:33
Oh, yeah! :) the @SpringBootApplication(exclude = SessionAutoConfiguration.class) together with Profiles worked like a charm.
In my use case I am using a specific implementation for the sessions with a strategy and all, so I see no value in exposing the auto-configuration. But that's just me, maybe others have different needs.
Thank you very much for your time!

**Comment by fedecz** [comment] 2016-01-21 06:57
Thanks for the explanation @shakuzen , I didn't know that.

I recently came across this class  `FlywayAutoConfiguration` and I liked the way that it uses `@ConditionalOnProperty` at the beginning to enable/disable everything, no matter if you already have a Datasource in your context or Flyway in your classpath.

I just thought it'd be a good idea to implement that in here.

Thanks again for your comments

Fede

**Comment by rwinch** [comment] 2016-02-05 05:10
Closing this one sine the issue seems to be resolved

**Closed by rwinch** 2016-02-05 05:10 UTC

**Comment by dfernandezm** [comment] 2016-07-06 19:26
This is still an issue in my case for Spring Boot app. @shakuzen I have done what you mention, but `afterPropertiesSet` is still invoked and trying to connect to Redis on startup (`org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration$EnableRedisKeyspaceNotificationsInitializer.afterPropertiesSet`)

I have the following config:

```
@EnableAutoConfiguration(exclude={RedisAutoConfiguration.class, RedisHttpSessionConfiguration.class, SessionAutoConfiguration.class, SessionAutoConfiguration.SessionRedisHttpConfiguration.class,
        SecurityAutoConfiguration.class, SecurityFilterAutoConfiguration.class, SpringBootWebSecurityConfiguration.class})
```

I see the answer from @youlib, which profile combination are you using? Is it to exclude this config as well?

I am using Spring Session 1.2.0.RELEASE and Spring Boot 1.3.0.RELEASE

**Comment by rwinch** [comment] 2016-07-06 19:27
@dfernandezm Thanks for the response. Can you please create a sample that demos the issue?

**Comment by dfernandezm** [comment] 2016-07-07 17:18
Thanks @rwinch, I'll prepare a reduced and focused version of the project in a Github repo and get back to you. The full project is hosted here (https://github.com/GraffiTab/GraffiTab-Backend).

**Comment by rwinch** [comment] 2016-07-07 17:40
Thanks @dfernandezm At first glance I don't see spring-session being used in that project, so I'm not sure how this pertains to Spring Session. Anyways...looking forward to the simplified sample. Please create a new ticket when you have the code to reproduce.

**Comment by michalkarolik** [comment] 2017-01-24 11:00
any ideas how to solve it? There is namespace available in yml/properties: spring.autoconfigure.exclude: but simply adding `org.springframework.boot.autoconfigure.session.SessionAutoConfiguration` doesnt switch spring session off.
