### ISSUE TITLE
support self-definition SessionIdGenerator

### ISSUE THREAD

**Issue by imaxun** [spring-projects/spring-session#2120] opened 2022-08-12 09:02 UTC
MapSession 
![image](https://user-images.githubusercontent.com/29112991/184321949-f916d3d5-ebdb-4024-ad78-0c0dd6872655.png)

**Comment by imaxun** [comment] 2022-08-12 10:57
hope support self-determination meeting id strategy

**Comment by imaxun** [comment] 2022-09-02 12:09
每人维护了么

**Comment by imaxun** [comment] 2022-09-02 12:10
没人维护了么

**Comment by imaxun** [comment] 2022-10-17 11:17
why?

**Comment by marcusdacoregio** [comment] 2023-07-27 18:32
Duplicate of #11

**Closed by marcusdacoregio** 2023-07-27 18:32 UTC
Labels: type: enhancement, status: waiting-for-triage
