### ISSUE TITLE
Spring Session On Apache Ignite

### ISSUE THREAD

**Issue by ryagnik** [spring-projects/spring-session#732] opened 2017-02-09 14:50 UTC
Thank you for building a http session agnostic framework.

I see spring session has an implementation with HazleCast,GemFire,Reddis and JDBC.

Do we have plan to add implementation for Apache Ignite ? is this something the team can take it on in near future ? 

Thanks,
Rishi

**Comment by vpavic** [comment] 2017-03-29 18:40
Closing as duplicate of #660.

**Closed by vpavic** 2017-03-29 18:40 UTC
Labels: question
