### ISSUE TITLE
is a bug about RedisSessionExpirationPolicy  method onDelete key is wrong?

### ISSUE THREAD

**Issue by zc888168** [spring-projects/spring-session#1515] opened 2019-09-25 08:37 UTC
I have found that RedisSessionExpirationPolicy class method onDelete can not delete.
My version is 2.1.8 and the code is 
this.redis.boundSetOps(expireKey).remove(session.getId())
is the key wrong?  shoud be "expires:" + session.getId().

**Comment by vpavic** [comment] 2019-09-27 13:03
The key is actually constructed on `RedisSessionExpirationPolicy#getExpirationKey`. The session id passed to `BoundSetOperations#remove` presents a value to be removed from the set.

Could you clarify what exactly is the problem, and how to reproduce it?

**Comment by spring-issuemaster** [comment] 2019-10-04 13:05
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Alwayswithme** [comment] 2019-10-08 07:00
@vpavic #1531 I create a simillar issue, please check

**Comment by spring-issuemaster** [comment] 2019-10-23 14:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-10-23 14:37 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
