### ISSUE TITLE
Spring Session (Redis) Keys not deleted...

### ISSUE THREAD

**Issue by sanjayagnani92** [spring-projects/spring-session#1017] opened 2018-03-08 09:09 UTC
Spring sessions(Redis): Keys Not deleted 
"spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:springbootuser"

IF users closes the session my hitting on logout the key gets deleted , but if session timeout this particular key is not deleted although it value is null after session timeout 

Is this key with empty value been used by actuator for session timeout count
Stackoverflow :https://stackoverflow.com/questions/44476205/spring-sessionsredis-findbyindexnamesessionrepository-principal-name-index-na

**Comment by sanjayagnani92** [comment] 2018-03-16 02:46
https://stackoverflow.com/questions/44476205/spring-sessionsredis-findbyindexnamesessionrepository-principal-name-index-na

**Comment by rameezrajas** [comment] 2018-03-21 04:05
We have the same issue as well. Only on logout spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME key is getting deleted

**Comment by rwinch** [comment] 2018-03-22 15:07
Perhaps a duplicate of https://jira.spring.io/browse/DATAREDIS-791

cc @mp911de

**Comment by mp911de** [comment] 2018-03-23 12:40
DATAREDIS-791 is related to reactive operations only. This one doesn't seem to have a WebFlux or other reactive affiliation.

**Comment by vpavic** [comment] 2018-03-23 20:28
@sanjayagnani92 @rameezrajas I'm unable to reproduce this, could you provide more info about your apps? Namely Spring Security and Spring Session releases that you use and their respective configurations.

If someone could put together a sample app that reproduces the problem, that would be of great help.

**Comment by rameezrajas** [comment] 2018-03-24 04:28
```java
package com.example.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.session.data.redis.config.annotation.web.http.EnableRedisHttpSession;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@EnableRedisHttpSession
@RestController
public class DemoApplication
{
  public static void main(String[] args)
  {
    SpringApplication.run(DemoApplication.class, args);
  }

  @GetMapping("/")
  public String index()
  {
    return "index";
  }
}
```

```java
package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter
{
  @Autowired
  public void configureGlobal(AuthenticationManagerBuilder auth) throws Exception
  {
    auth.inMemoryAuthentication().withUser("user").password("password").roles("USER");
  }
}
```

![image](https://user-images.githubusercontent.com/19847319/37860376-caeebcfe-2ee0-11e8-8ef5-c0efa338fe20.png)

**Comment by vpavic** [comment] 2018-03-24 08:12
Thanks @rameezrajas, however this still works in my environment.

What version of Redis do you use? Also could you configure debug log level for `org.springframework.session.data.redis.RedisOperationsSessionRepository` and see if you're having entries starting with `Publishing SessionDestroyedEvent for session` logged (see [`RedisOperationsSessionRepository:527`](https://github.com/spring-projects/spring-session/blob/1.3.1.RELEASE/spring-session/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L522)).

**Comment by rameezrajas** [comment] 2018-03-24 16:01
2018-03-24 08:59:51.966  INFO 15456 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-03-24 08:59:51.966  INFO 15456 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-03-24 08:59:51.988  INFO 15456 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 22 ms
2018-03-24 09:00:00.019 DEBUG 15456 --- [pool-1-thread-1] o.s.s.d.r.RedisSessionExpirationPolicy   : Cleaning up sessions expiring at Sat Mar 24 09:00:00 PDT 2018
2018-03-24 09:00:03.952 DEBUG 15456 --- [enerContainer-3] s.s.d.r.RedisOperationsSessionRepository : Publishing SessionDestroyedEvent for session 890eca70-8970-40da-8759-9d446e385e75

**Comment by vpavic** [comment] 2018-03-26 13:06
I was able to reproduce the described behavior by shutting down Redis server after an app that uses Spring Session has started, and then bringing the server back on.

Are you experiencing connectivity loss toward Redis server in your case as well @rameezrajas? This can be recognized in the logs by the following entries:

```
org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Connection reset; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:67) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:241) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.close(JedisConnection.java:335) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.closeConnection(RedisMessageListenerContainer.java:875) [spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.handleSubscriptionException(RedisMessageListenerContainer.java:644) [spring-data-redis-1.8.10.RELEASE.jar:na]
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.run(RedisMessageListenerContainer.java:756) [spring-data-redis-1.8.10.RELEASE.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_152]
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:202) ~[jedis-2.9.0.jar:na]
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:151) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:215) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:340) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:239) ~[jedis-2.9.0.jar:na]
	at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:253) ~[jedis-2.9.0.jar:na]
	at org.springframework.data.redis.connection.jedis.JedisConnection.close(JedisConnection.java:325) ~[spring-data-redis-1.8.10.RELEASE.jar:na]
	... 4 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[na:1.8.0_152]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_152]
	at java.net.SocketInputStream.read(SocketInputStream.java:127) ~[na:1.8.0_152]
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:196) ~[jedis-2.9.0.jar:na]
	... 11 common frames omitted

2018-03-26 14:08:05.566 ERROR 29334 --- [enerContainer-1] o.s.d.r.l.RedisMessageListenerContainer  : Connection failure occurred. Restarting subscription task after 5000 ms
```

I've opened #1030 to track that issue.

If the connectivity loss is not the case, could you please try running Redis server in a Docker container? The Windows service is, AFAIK, not an official Redis distribution and your issues might be related to that. 

If that doesn't help either, please provide a sample app that we can download together with detailed instructions on how to reproduce the problem.

**Comment by rameezrajas** [comment] 2018-03-26 18:13
i do not see connectivity loss toward Redis server. By the way, this issue not only happens in windows service. It happens in our production environment as well. in prod, we a azure managed redis.

**Comment by vpavic** [comment] 2018-04-13 11:09
@rameezrajas Did you ensure your Redis server is configured according to this part of my previous comment?

> Make sure to refer to [`SessionDeletedEvent` and `SessionExpiredEvent` related sections of Redis configuration](https://docs.spring.io/spring-session/docs/2.0.2.RELEASE/reference/html5/#api-redisoperationssessionrepository-sessiondestroyedevent) as this might be the cause of your problems related to handling of session destroyed events.

**Comment by vpavic** [comment] 2018-05-02 04:48
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please re-open the issue.

**Closed by vpavic** 2018-05-02 04:48 UTC
Labels: waiting for feedback

**Comment by cablespaghetti** [comment] 2020-06-08 15:13
@vpavic I appreciate this is a very old issue but I'm struggling with this problem and hope you can see what I'm doing wrong. Our production environment has about 11000 items in the index even though there are less than 50 active sessions and it keeps increasing over time.

We are using version 1.3.5 (because the application is Spring 4) and Jedis 2.8.2. Here's our configuration class:
https://gist.github.com/cablespaghetti/6f0e8e9d45795a300768b95391172313

And redis is set up in all environments with notify-keyspace-events Egx. Production is on redis 3.2 but dev is on 4 and we still have the issue there.

I think everything is set up properly. I initially thought that this was to do with my application being autoscaled but the problem still happens running a single instance of it locally with a single standalone redis.

Here are some logs from my application:
```
cms-api_1             | 2020-06-08 14:01:49,085 [redisMessageListenerContainer-11] DEBUG org.springframework.session.data.redis.RedisOperationsSessionRepository - Publishing SessionDestroyedEvent for session b65f84ed-e61c-4231-9561-3a2733fd0923
cms-api_1             | 2020-06-08 14:01:49,085 [redisMessageListenerContainer-11] DEBUG org.springframework.session.data.redis.RedisOperationsSessionRepository - Publishing SessionDestroyedEvent for session b65f84ed-e61c-4231-9561-3a2733fd0923
cms-api_1             | 2020-06-08 14:02:00,000 [pool-81-thread-1] DEBUG org.springframework.session.data.redis.RedisSessionExpirationPolicy - Cleaning up sessions expiring at Mon Jun 08 14:02:00 UTC 2020
cms-api_1             | 2020-06-08 14:02:00,001 [pool-82-thread-1] DEBUG org.springframework.session.data.redis.RedisSessionExpirationPolicy - Cleaning up sessions expiring at Mon Jun 08 14:02:00 UTC 2020
```

I thought about writing a script to clean up the index but I'm not quite sure how to do that.

Many thanks

**Comment by vpavic** [comment] 2020-06-23 10:16
@cablespaghetti, could you open a new issue based on your comment, so it doesn't get lost (as this issue's been closed for a while)?
