### ISSUE TITLE
Wrong letter case in table 'spring_session_attributes' with Spring Session JDBC

### ISSUE THREAD

**Issue by AlesAlitis** [spring-projects/spring-session#1754] opened 2021-01-15 09:33 UTC
**Describe the bug**
When DB tables for JDBS session repository are created manually, sometimes this exception is thrown:
`java.sql.SQLSyntaxErrorException: Table 'shema_name.spring_session_ATTRIBUTES' doesn't exist`.
This expected as the table name is all lower case. The same code works fine in DEV environment but throws the exception deployed for testing. 
Also, I've noticed that sometimes the case of "_ATTRIBUTES" changes between application restarts.

The only configuration done is this application property:
`spring.session.jdbc.table-name=spring_session`
Everything else is auto configured.

**To Reproduce**
Create tables with this SQL:
```
create table spring_session
(
    PRIMARY_ID            char(36)     not null
        primary key,
    SESSION_ID            char(36)     not null,
    CREATION_TIME         bigint       not null,
    LAST_ACCESS_TIME      bigint       not null,
    MAX_INACTIVE_INTERVAL int          not null,
    EXPIRY_TIME           bigint       not null,
    PRINCIPAL_NAME        varchar(100) null,
    constraint SPRING_SESSION_IX1
        unique (SESSION_ID)
);

create index SPRING_SESSION_IX2
    on spring_session (EXPIRY_TIME);

create index SPRING_SESSION_IX3
    on spring_session (PRINCIPAL_NAME);

create table spring_session_attributes
(
    SESSION_PRIMARY_ID char(36)     not null,
    ATTRIBUTE_NAME     varchar(200) not null,
    ATTRIBUTE_BYTES    blob         not null,
    primary key (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    constraint SPRING_SESSION_ATTRIBUTES_FK
        foreign key (SESSION_PRIMARY_ID) references spring_session (PRIMARY_ID)
            on delete cascade
);
```

Set JDBC session repository with:
`spring.session.jdbc.table-name=spring_session`

Deploy the code in two different environments.

**Expected behaviour**
The code should match the case of the name given in the application.properties.

**Comment by eleftherias** [comment] 2021-01-20 11:09
@AlesAlitis 

It is not the expected behaviour that the table name should match the case of the name given in application.properties.

From the `JdbcIndexedSessionRepository ` Javadoc:

>By default, this implementation uses SPRING_SESSION and SPRING_SESSION_ATTRIBUTES tables to store sessions. Note that the table name can be customized using the setTableName(String) method. In that case the table used to store attributes will be named using the provided table name, suffixed with _ATTRIBUTES.

In the case that you set `spring.session.jdbc.table-name=spring_session`, the table used to store the attributes will be named `spring_session_ATTRIBUTES`.

You mention that the same code works fine in DEV environment but throws the exception deployed for testing.
Are you using different databases in those environments? 
In some databases table names in a query are case sensitive, while in others they are not case sensitive.

**Comment by AlesAlitis** [comment] 2021-01-20 11:45
@eleftherias 
In my DEV environment the attributes table is all lowercase: spring_session_attributes.
Also, in at least one case, the application changed the table name it was querying from spring_session_attributes to spring_session_ATTRIBUTES and back again between restarts.

Although the uppercase conflicts with the naming convention I use, it's not that big of an issue. I'm more concerned with the inconsistency.

Here some more details:

DEV:
Windows 10
MySQL 8.0.22
Apache Tomcat 9.0.37

TEST:
CentOS 7
MySQL 8.0.17
Apache Tomcat 9.0.37

**Comment by eleftherias** [comment] 2021-01-20 12:57
Thanks for the information @AlesAlitis.

The table name is all lowercase because the SQL script that creates it names it `spring_session_attributes`, however Spring Session expects it to be named `spring_session_ATTRIBUTES`.

All Spring Session queries will use the table name `spring_session_ATTRIBUTES`.

It's surprising to me that the application changed the table name it was querying from `spring_session_attributes` to `spring_session_ATTRIBUTES` and back again between restarts.

I would expect that it would never query `spring_session_attributes`.

Are the mentioned queries all coming from Spring Session or do you have custom queries as well?

**Comment by AlesAlitis** [comment] 2021-01-20 13:46
@eleftherias 
All session related queries are coming from Spring Session.
I checked the MySQL documentation: case sensitivity of table names and aliases depends on the host OS. That explains why it works fine in DEV and not in TEST.

**Comment by eleftherias** [comment] 2021-01-21 11:40
That makes sense @AlesAlitis.
Is that sufficient information to close this issue or is there still an unanswered question?

**Comment by AlesAlitis** [comment] 2021-01-22 09:41
That is good enough for me @eleftherias

**Closed** 2021-01-22 09:51 UTC
Labels: status: feedback-provided
