### ISSUE TITLE
Exclude classes from deserialization

### ISSUE THREAD

**Issue by khauser** [spring-projects/spring-session#570] opened 2016-07-12 06:38 UTC
Hi there,

I have set up a running microservice infrastructure (https://github.com/khauser/microservices4vaadin) based on:
- Spring-Boot 1.3.5
- Spring Session 1.2.1
- Spring Data Redis 1.7.2
- Jedis 2.8.1
- Vaadin 7.6.7
- and "some" others ..

In this scenario spring session (+redis) is used to share a common session overall microservices having the `@EnableRedisHttpSession`-tag (authserver, edge, frontend). In order to get this run I had to add some dirty hacks where you might have some over proposals.

The problem is that all services try to deserialize the whole objects stored in the session. In spite of User and Authorisation data this is fine, all the enable services need them and do have the related classes. But for example the frontend (implemented with vaadin) additionally needs to store also the `VaadinSession`-object which definitely is not needed by the other services. Thats why I have adjusted the deserialization process within spring-session by adding 

``` java
if(!key.contains("springVaadinServlet"))
                map.put((HK) deserializeHashKey(entry.getKey()), (HV) deserializeHashValue(entry.getValue()));
```

to line 280 in org.springframework.data.redis.core.AbstractOperations.java. Now the other services (authserver, edge) ignore the data form the Vaadin session.

Is there another way to achieve the same behavior, maybe a "exclude classes from deserialization"-feature?

Thanks for you help!
Karsten

**Comment by tamimcsedu19** [comment] 2019-06-04 05:15
I have the same problem. Any way to fix this without messing with spring code?

**Comment by rwinch** [comment] 2019-06-04 19:13
@tamimcsedu19 There is no built in way at the moment. 

I'm closing this as a duplicate of gh-529

**Closed by rwinch** 2019-06-04 19:13 UTC
Labels: status: duplicate
