### ISSUE TITLE
Cannot create a session after the response has been committed

### ISSUE THREAD

**Issue by kaixinwangzi1982** [spring-projects/spring-session#793] opened 2017-05-30 16:25 UTC
```
Servlet.service() for servlet [CometServlet] in context with path [] threw exception
java.lang.IllegalStateException: Cannot create a session after the response has been committed
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2921)
	at org.apache.catalina.connector.Request.getSession(Request.java:2318)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:899)
	at org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:911)
	at com.pms.utils.CometUtil.handleEvent(CometUtil.java:39)
	at com.pms.utils.CometUtil.handleEvent(CometUtil.java:16)
	at org.comet4j.event.EventSource.fire(EventSource.java:39)
	at org.comet4j.event.Observable.fireEvent(Observable.java:104)
	at org.comet4j.core.CometEngine.connect(CometEngine.java:84)
	at org.comet4j.core.CometServlet.event(CometServlet.java:43)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilterEvent(ApplicationFilterChain.java:484)
	at org.apache.catalina.core.ApplicationFilterChain.doFilterEvent(ApplicationFilterChain.java:377)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1721)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
This is my issue, when not integrating spring-session. Comet works. But now, it does now work.
This is my web.xml following:

```xml
	<!-- Spring Listener -->
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>
            classpath:/applicationContext.xml
        </param-value>
	</context-param>
	
	<!-- 过滤器 spring-session -->
    <filter>
        <filter-name>springSessionRepositoryFilter</filter-name>
        <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>springSessionRepositoryFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>ERROR</dispatcher>
    </filter-mapping>
    
	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>
	
	<!-- Character Filter -->
	<filter>
		<filter-name>CharacterEncodingFilter</filter-name>
		<filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>
		<init-param>
			<param-name>encoding</param-name>
			<param-value>UTF-8</param-value>
		</init-param>
		<init-param>
			<param-name>forceEncoding</param-name>
			<param-value>true</param-value>
		</init-param>
	</filter>
	<filter-mapping>
		<filter-name>CharacterEncodingFilter</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
	
	
    
    
	<listener>
		<listener-class>org.springframework.web.util.WebAppRootListener</listener-class>
	</listener>

	<listener>
		<listener-class>org.springframework.web.context.request.RequestContextListener</listener-class>
	</listener>
	<!-- <listener>
 		 <listener-class>com.pms.wx.listener.TaskListener</listener-class>
    </listener> -->
    
	<context-param>
		<param-name>logbackConfigLocation</param-name>
		<param-value>classpath:logback.xml</param-value>
	</context-param>
	<listener>
		<listener-class>ch.qos.logback.ext.spring.web.LogbackConfigListener</listener-class>
	</listener>

    <listener>
        <description>Comet4J容器侦听</description>
        <listener-class>org.comet4j.core.CometAppListener</listener-class>
    </listener>
    <listener>
        <description>监听我们自己的推送类</description>
        <listener-class>com.pms.utils.CometUtil</listener-class>
    </listener>
    <servlet>
        <description>客户端访问入口</description>
        <servlet-name>CometServlet</servlet-name>
        <servlet-class>org.comet4j.core.CometServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>CometServlet</servlet-name>
        <url-pattern>/servlet/conn</url-pattern>
    </servlet-mapping>
```

**Comment by rwinch** [comment] 2017-05-30 19:15
I am new to comment, so I would need a complete and minimal sample along with instructions on how to reproduce to help trouble shoot this. I do not see Spring Session in the stacktrace you provided, so it does not appear that Spring Session is being used for this request.

**Comment by rwinch** [comment] 2017-05-30 19:15
PS: You can use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)  for formatting code. For example:


    ```java
    System.out.println("hi");
    System.out.println("there");
    ```

will render as

```java
System.out.println("hi");
System.out.println("there");
```

**Comment by kaixinwangzi1982** [comment] 2017-05-31 03:00
When request this jsp. the code following:
<script type="text/javascript" src="${basePath}/js/common.js"></script>

<script src="/js/plugins/iCheck/icheck.min.js"></script>
<script type="text/JavaScript" src="/js/plugins/comet/comet4j.js"></script>
<script type="text/javascript">
layui.use('element', function(){
	  var $ = layui.jquery
	  ,element = layui.element(); //Tab的切换功能，切换事件监听等，需要依赖element模块
	  //触发事件
	  function setPercent(id,no){
	      //设置50%进度
	      element.progress(id, no);
	  }
	  // 建立连接，conn 即web.xml中 CometServlet的<url-pattern>
      JS.Engine.start('/servlet/conn');
      <c:set var="currentUserId" value="${currentUserId}" scope="session"/>
      // 监听后台某个频道
      JS.Engine.on({ 
            // 对应服务端 “频道1” 的值 msgCount
            msg : function(vo){
            	$('#'+'div'+vo.houseId).html('更新中...');
            	$('#'+'div'+vo.houseId).attr("disabled", true);
            	document.getElementById('div' +vo.houseId).disabled=true;
            	$('#'+vo.houseId+'div').show();
            	setPercent(vo.houseId,vo.percent);
            	if(vo.flag == 1){           		
            	$('#'+ 'div' +vo.houseId).html('更新成功');
            	$('#num').html(vo.num);
            	} 
            	if(vo.flag == 2){
            	$('#'+ 'div' +vo.houseId).html('更新失败');
            	$('#errNum').html(vo.errNum);
            	}
            	Dialog.msg(vo.msg);
            }
        }
      );
	});
</script>
<script type="text/javascript" src="/scripts/subproj/quickpublish/quickPublishSina.js?v=20170515"></script>
</body>
</html>

This request is called automatically :       JS.Engine.start('/servlet/conn');   ,and it configed in web.xml, it is part of Comet,

<listener>
        <description>Comet4J容器侦听</description>
        <listener-class>org.comet4j.core.CometAppListener</listener-class>
    </listener>
    <listener>
        <description>监听我们自己的推送类</description>
        <listener-class>com.pms.utils.CometUtil</listener-class>
    </listener>
    <servlet>
        <description>客户端访问入口</description>
        <servlet-name>CometServlet</servlet-name>
        <servlet-class>org.comet4j.core.CometServlet</servlet-class>
    </servlet>
    <servlet-mapping>
        <servlet-name>CometServlet</servlet-name>
        <url-pattern>/servlet/conn</url-pattern>
    </servlet-mapping>


When I check CometServlet sourceCode ,it like this 
public class CometServlet extends HttpServlet implements CometProcessor {
	private static final long serialVersionUID = 1L;

	public void event(CometEvent event) throws IOException, ServletException {
		HttpServletRequest request = event.getHttpServletRequest();
		HttpServletResponse response = event.getHttpServletResponse();
		request.setAttribute("org.apache.tomcat.comet.timeout",
				Integer.valueOf(CometContext.getInstance().getTimeout()));
		event.setTimeout(CometContext.getInstance().getTimeout());
		if (event.getEventType() == EventType.BEGIN) {
			String action = request.getParameter("cmd");
			if ("conn".equals(action)) {
				CometContext.getInstance().getEngine().connect(request, response);
			} else if ("revival".equals(action)) {
				CometContext.getInstance().getEngine().revival(request, response);
			} else if ("drop".equals(action)) {
				CometContext.getInstance().getEngine().drop(request, response);
			}
		} else if (event.getEventType() == EventType.ERROR) {
			if (event.getEventSubType() == EventSubType.TIMEOUT) {
				CometContext.getInstance().getEngine().dying(request, response);
			} else {
				CometContext.getInstance().getEngine().drop(request, response);
			}
		} else if (event.getEventType() == EventType.END) {
			CometContext.getInstance().getEngine().dying(request, response);
		} else {
			event.getEventType();
			EventType arg9999 = EventType.READ;
		}

	}

	public void destroy() {
		super.destroy();
	}
}


And this is my CometUtil part or sourceCode:

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;

import org.comet4j.core.CometConnection;
import org.comet4j.core.CometContext;
import org.comet4j.core.CometEngine;
import org.comet4j.core.event.ConnectEvent;
import org.comet4j.core.listener.ConnectListener;

import com.comet.CacheManager;
import com.comet.Comet;
import com.pms.utils.constants.Constants;

public class CometUtil extends ConnectListener implements ServletContextListener {
	/**
	 * 初始化上下文
	 */
	public void contextInitialized(ServletContextEvent arg0) {
		// CometContext ： Comet4J上下文，负责初始化配置、引擎对象、连接器对象、消息缓存等。
		CometContext cc = CometContext.getInstance();
		// 注册频道，即标识哪些字段可用当成频道，用来作为向前台传送数据的“通道”
		cc.registChannel(Constants.CHANNEL_MSG);
		// 添加监听器
		CometEngine engine = CometContext.getInstance().getEngine();
		engine.addConnectListener(this);
	}

	@Override
	public void contextDestroyed(ServletContextEvent sce) {
		// TODO Auto-generated method stub
	}

	@Override
	public boolean handleEvent(ConnectEvent connEvent) {
		// TODO Auto-generated method stub
		final CometConnection conn = connEvent.getConn();
		Object userId = conn.getRequest().getSession().getAttribute("currentUserId");
		CacheManager.putContent(userId.toString(), connEvent);
		return true;
	}

when running this code "Object userId = conn.getRequest().getSession().getAttribute("currentUserId");" errors occured.

Thanks for your replying!

**Comment by spring-issuemaster** [comment] 2020-12-15 17:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-22 17:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-22 17:42 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
