### ISSUE TITLE
Problem with SessionRegistry used with ConcurrentSessionControlAuthenticationStrategy in distributed env

### ISSUE THREAD

**Issue by rajeevpandey-pt** [spring-projects/spring-session#127] opened 2015-01-28 12:06 UTC
ConcurrentSessionControlAuthenticationStrategy have default implementation of SessionRegistry as SessionRegistryImpl that have all the principles in hash map. In case of distributed application if a duplicate session identified and ConcurrentSessionControlAuthenticationStrategy expires the least recently used session, then that will be expired in first server only and if next request comes to second server then SessionRegistryImpl will return the session that have been invalidated on the first server.

So in case of session being stored in redis, there should be another implementation of  SessionRegistry over redis and that should not cache the principle rather it should get that from redis.

**Comment by rwinch** [comment] 2015-01-28 15:38
Thank you for the report. This is a duplicate of https://github.com/spring-projects/spring-session/issues/65

**Closed by rwinch** 2015-01-28 15:38 UTC
Labels: duplicate

**Comment by rajeevpandey-pt** [comment] 2015-01-29 11:53
Thanks for the quick response @rwinch. Although i got a work around to deal with this as using ConcurrentSessionFilter with CookieClearingLogoutHandler and SecurityContextLogoutHandler, and deleting the session from redis in RedirectStrategy for session expiry.

**Comment by rwinch** [comment] 2015-01-29 15:19
Glad you found a workaround. If you are willing,  you might provide more details on your workaround on the referenced issue. This may help others to be able to use a similar work around.

Thanks again for reporting this!

**Comment by yacota** [comment] 2015-01-30 07:52
+1 to @rwinch comment. Could you please provide more details ?

**Comment by rajeevpandey-pt** [comment] 2015-02-01 09:20
I am pleased to share the details of referenced issue, scenario is that we have REST APIs for login and logout using spring security and spring session, deployed in clustered tomcat environment, redis and database is shared among those tomcat.
I have provided a custom implementation  of RedisOperationsSessionRepository to store session in redis as well as in database and configured that in SessionRepositoryFilter.
To handle duplicate session configured ConcurrentSessionFilter with SessionRegistryImpl for session registry, CookieClearingLogoutHandler and SecurityContextLogoutHandler for logout handlers, and a custom RedirectStrategy with RedisOperationsSessionRepository to handle expired session.
UsernamePasswordAuthenticationFilter is configured with ConcurrentSessionControlAuthenticationStrategy to handle duplicate login that marks least recently used session invalid. So when that session attempts to call API that needs authentication,  ConcurrentSessionFilter will invoke logout handlers to clear that cookie and clear the context for that session, and invoke RedirectStrategy where I am deleting that session from redis and database.
The problem I was facing with multiple tomcats was because of these two points
1. ConcurrentSessionFilter was configured with only CookieClearingLogoutHandler so even though it cleared cookie but when control reaches back to ConcurrentSessionFilter it creates cookie again because session is there that it got from redis/database.
2. And I was not deleting session from redis and database in RedirectStrategy.
So clearing the session from context and redis/database in case of duplicate session solved my problem.

**Comment by yacota** [comment] 2015-02-02 08:39
Thanks @rajeevpandey-pt

**Comment by praptin** [comment] 2015-06-04 07:18
@rajeevpandey-pt can you give me example code? I'm having the same problem after user logout, SessionInformation in SessionRegistry not deleted properly.
Thanks

**Comment by mohsen-mahmoudi** [comment] 2015-08-27 06:05
Hi Mr. @rwinch ..
with your remarks, is this problem (https://github.com/spring-projects/spring-session/issues/281) solved? if solved!, what i must do?
is solved in spring security 4.1?
