### ISSUE TITLE
Spring-session catch an exception when removeAttribute(or clear session) 

### ISSUE THREAD

**Issue by zhangmeng0426** [spring-projects/spring-session#896] opened 2017-10-12 08:31 UTC
Spring session version 1.2.0
cache is redis
struts2-2.3.32
JDK 1.8

when I clear the session, 
   **my code is :** 
                      session = ActionContext.getContext().getSession();
		      session.clear();
   **struts2 code is :** 
                      synchronized (session.getId().intern()) {
                             Enumeration<String> attributeNamesEnum = session.getAttributeNames();
                             while (attributeNamesEnum.hasMoreElements()) {
                                     session.removeAttribute(attributeNamesEnum.nextElement());
                              }
                         }
   **when catch the exception ,info is :** 
      **java.util.ConcurrentModificationException**
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at java.util.Collections$3.nextElement(Collections.java:5216)
        at org.apache.struts2.dispatcher.SessionMap.clear(SessionMap.java:94)
        at com.merchant.action.MerchantManageAction.modifyUserMobilePhone(MerchantManageAction.java:361)
   
     thanks!

**Comment by zhangmeng0426** [comment] 2017-10-12 08:32
**test servlet**  

protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		HttpSession session = request.getSession();
		session.setAttribute("abc", 123);
		session.setAttribute("bcd", 4563+"你好");
		System.out.println("Session ID = "+ session.getId());
		System.out.println("Session value = " + session.getAttribute("bcd"));
		
		synchronized (session.getId().intern()) {
            Enumeration<String> attributeNamesEnum = session.getAttributeNames();
            while (attributeNamesEnum.hasMoreElements()) {
                session.removeAttribute(attributeNamesEnum.nextElement());
            }
        }
	}

**Comment by eleftherias** [comment] 2021-12-13 12:33
Thanks for getting in touch @zhangmeng0426 and I'm sorry about the late reply.
Do you have a [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this issue?

**Comment by spring-projects-issues** [comment] 2021-12-20 12:38
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-01-04 09:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-01-04 09:59 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
