### ISSUE TITLE
Almost impossible to extend the RedisIndexedSessionRepository class

### ISSUE THREAD

**Issue by j75** [spring-projects/spring-session#1562] opened 2020-01-24 12:28 UTC
Although not marked as final, the class _RedisIndexedSessionRepository_ could not be easily extended ; more precisely, the _createSession()_ could not be overriden, as the _RedisSession_ class is not visible.
What about modifying the signature of this class to return a _Session_ instance?

**Comment by marcusdacoregio** [comment] 2023-08-08 14:51
Duplicate of #2258

**Closed by marcusdacoregio** 2023-08-08 14:51 UTC
Labels: status: duplicate
