### ISSUE TITLE
Support for sticky sessions

### ISSUE THREAD

**Issue by Thilak-T** [spring-projects/spring-session#146] opened 2015-02-12 06:58 UTC
It would be great if spring-session supports sticky sessions and optimizations aroud it, as we need this feature for our production deployment. Willing to put effort for this project if needed. Thanks

**Comment by chrylis** [comment] 2015-02-12 07:23
What exactly do you mean by sticky sessions? That's usually an issue for the load balancer.

**Comment by Thilak-T** [comment] 2015-02-12 07:28
I mean a way to tell spring-session that the app uses sticky session concept, so that the app primarily read-write on local session object and a replica is maintained on redis for fail-over. If the local session object is lost for some reason, spring-session tries to get from redis.

**Comment by rwinch** [comment] 2015-08-03 16:37
This is a duplicate of #6

**Closed by rwinch** 2015-08-03 16:37 UTC
