### ISSUE TITLE
Unable to publish SessionDestroyedEvent

### ISSUE THREAD

**Issue by zeronone** [spring-projects/spring-session#1047] opened 2018-04-12 08:24 UTC
I am currently using 1.3.2 and gettings warnings logged from [here](https://github.com/spring-projects/spring-session/commit/6a6d60d8f8a545584ecbcb46be341e3175144f72#diff-393b6da0aa45a16e7b5f23fd95ae94e9R523). 

I also found that 2.0 and 1.3.2 handles it differently. Is there any reason?
1.3.2 ([here](https://github.com/spring-projects/spring-session/commit/6a6d60d8f8a545584ecbcb46be341e3175144f72#diff-393b6da0aa45a16e7b5f23fd95ae94e9R523))
2.0.0 ([here](https://github.com/spring-projects/spring-session/blob/master/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisOperationsSessionRepository.java#L522)).

**Comment by vpavic** [comment] 2018-04-12 11:02
Thanks for the report @zeronone.

You might want to take a look at #499 for more background on the problem and this issue effectively duplicates it, since you're using Spring Session 1.x.

Regarding the difference in handling between the 1.x and 2.x, the missing `return` statement in 1.x does indeed seem fishy. Can you tell me is the logged warning followed by a `NullPointerException` in your case?

**Comment by vpavic** [comment] 2018-04-12 15:56
Thanks for the quick follow-up @zeronone, the NPE is a bug introduced by #984. Funny thing is, that issue was intended to address a NPE reported in #499 by handling the NPE and improving the logging, but it ended up introducing NPE in a different place. I've opened #1049 to track that.

BTW if you can provide us with a sample and instructions how to reproduce the sequence of actions which lead to this situation, please follow up on #499 as that would be of great help. I'm going to close this one as duplicate.

Regarding the question on events and multiple nodes - that's exactly the point, the `HttpSessionEvent` should be observed on all instances of the app that form a cluster. At that point, it's up to your app to decide what to do in event listener. Note that for `SessionRepository` implementations that use data stores which don't have capabilities to support cluster-wide propagation of session events, such as `JdbcOperationsSessionRepository`, we don't support event publishing.

Duplicate of #499.

**Closed by vpavic** 2018-04-12 15:56 UTC
Labels: waiting for feedback
