### ISSUE TITLE
Unexpected end of stream

### ISSUE THREAD

**Issue by zhanglei-1987** [spring-projects/spring-session#1556] opened 2019-12-20 08:53 UTC
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:202)
	at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
	at redis.clients.jedis.Protocol.process(Protocol.java:155)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
	at redis.clients.jedis.Jedis.clusterInfo(Jedis.java:3337)
	at org.springframework.data.redis.connection.ClusterCommandExecutor.executeCommandOnSingleNode(ClusterCommandExecutor.java:144)
	... 98 common frames omitted

**Comment by eleftherias** [comment] 2020-02-12 16:19
@zhanglei-1987 Can you please add more detail to this report?
In order to help diagnose this issue please provide:
- The dependencies and versions that you are using
- The steps to reproduce this error

**Comment by spring-issuemaster** [comment] 2020-02-19 16:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-02-26 16:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-02-26 16:23 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
