### ISSUE TITLE
NoSuchMethodError when invoking RedisOperationsSessionRepository.delete

### ISSUE THREAD

**Issue by asha-chandran** [spring-projects/spring-session#1346] opened 2019-03-11 09:57 UTC
I'm using spring session and spring data redis for session management. I haven't used Spring boot.

Used are as follows,

    spring-session: 1.3.5.RELEASE
    spring-data-redis: 2.1.4.RELEASE
    spring-webmvc: 5.0.4.RELEASE
    lettuce-core: 5.1.4.RELEASE

Included these beans for redis configuration:
org.springframework.session.data.redis.config.annotation.web.http.RedisHttpSessionConfiguration, org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.

Included filter springSessionRepositoryFilter in web.xml.

But I got following error frequently.

```
ERROR org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NoSuchMethodError: org.springframework.data.redis.core.RedisOperations.delete(Ljava/lang/Object;)V
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:132) ~[spring-session-1.3.5.RELEASE.jar:?]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:398) ~[spring-session-1.3.5.RELEASE.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by vpavic** [comment] 2019-03-12 14:57
As explained in spring-projects/spring-framework#22538, this is due to use of incompatible dependency versions.

If you're using Spring Framework 5.x you need to upgrade to Spring Session 2.x. I again encourage you to take a look at [_Upgrading to 2.x_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#upgrading-2.0) of Spring Session reference manual.

**Comment by asha-chandran** [comment] 2019-03-13 06:38
> As explained in [spring-projects/spring-framework#22538](https://github.com/spring-projects/spring-framework/issues/22538), this is due to use of incompatible dependency versions.
> 
> If you're using Spring Framework 5.x you need to upgrade to Spring Session 2.x. I again encourage you to take a look at [_Upgrading to 2.x_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#upgrading-2.0) of Spring Session reference manual.

Okay. From where do I get spring session 2.x? Mine is Maven project and in maven repository(central) latest I could download is spring session 1.3.5.

**Comment by vpavic** [comment] 2019-03-13 07:32
@asha-chandran I've repeatedly pointed you to the [_Upgrading to 2.x_ section](https://docs.spring.io/spring-session/docs/current/reference/html5/#upgrading-2.0) of Spring Session reference manual because all the relevant information you need really is in there:

> As a part of the project’s split the modules, the existing `spring-session` has been replaced with `spring-session-core` module. The `spring-session-core` module holds only the common set of APIs and components while other modules contain the implementation of appropriate `SessionRepository` and functionality related to that data store.

Searching Maven Central would also help:
https://search.maven.org/search?q=g:org.springframework.session

**Comment by vpavic** [comment] 2019-04-17 05:28
Closing as answered. If you have additional questions or feel that your original question isn't properly answered, please comment back and we can re-open the issue.

**Closed by vpavic** 2019-04-17 05:28 UTC
Labels: waiting for feedback

**Comment by TonnyPaulose** [comment] 2021-06-02 03:57
I have upgraded the spring session version to spring-session-2.0.0.M2.jar , still, I am getting the same exception.

When I open the jar file I can see the delete method. So I created a package with the name org.springframework.session.data.redis and copied RedisSessionExpirationPolicy class from jar file. then the issue is resolved. 
I am not sure really its a dependency version issue
