### ISSUE TITLE
PRINCIPAL_NAME_INDEX_NAME how to clean up manually

### ISSUE THREAD

**Issue by hieastz** [spring-projects/spring-session#2647] opened 2023-11-21 06:17 UTC
My Redis is not support  notify keyspace events, Config ConfigureRedisAction.NO_OP is Bean.

I found that PRINCIPAL_NAME_INDEX_NAME index was not cleaned up（At the same time, the program will not be cleaned up when it is down）.

Now I want to clean up the PRINCIPAL_NAME_INDEX_NAME index manually, bothering to guide where to execute it, and it is better to provide code samples.

Thank you!

**Comment by marcusdacoregio** [comment] 2023-12-12 13:30
Hi, @hieastz. This seems a duplicate of https://github.com/spring-projects/spring-session/issues/2614.

Let's keep the discussion there as I already provided some context.

**Closed by marcusdacoregio** 2023-12-12 13:30 UTC
Labels: status: duplicate, type: enhancement
