### ISSUE TITLE
How keep login when one of server stop to maintain?

### ISSUE THREAD

**Issue by vohoangnhat** [spring-projects/spring-session#1435] opened 2019-05-28 09:16 UTC
I built the load balancer system as follows:

![image](https://user-images.githubusercontent.com/42776079/58465967-f3e28e80-8162-11e9-9934-898ed8b8e1f1.png)

nginx.conf:

```
upstream backend {	
	     ip_hash;
             server 127.0.0.1:8080; 
              server 192.168.100.88:8080; 
}
server {
        listen       80;
        server_name  localhost;
       location / {
                        proxy_pass http://backend;
			proxy_next_upstream   error timeout invalid_header http_500;
			proxy_connect_timeout 2;
		}
}
```
When I stop server 1 or server 2 to maintenance, the entire user session is lost and the user has to login again. Please help me, is there any way to keep the user login session? Sorry my bad English

**Comment by vpavic** [comment] 2019-05-31 20:09
Are you using Spring Session? If yes, can you clarify how the problem is related to Spring Session and provide relevant configuration or even better, a minimal and complete sample that reproduces the problem?

**Comment by spring-issuemaster** [comment] 2019-06-07 20:13
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-06-14 20:13
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-06-14 20:13 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
