### ISSUE TITLE
Spring-session and spring-social

### ISSUE THREAD

**Issue by hlassiege** [spring-projects/spring-session#210] opened 2015-05-21 16:39 UTC
Hi,

Sometimes I have some exception in the logs about the fact that a bean is not serializable : 

```
t=http-nio-8443-exec-13 l=ERROR c=o.a.c.c.C.[.[.[.[dispatcherServlet] m=Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception java.io.NotSerializableException: org.springframework.social.security.SocialAuthenticationServiceRegistry
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[na:1.8.0_25]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548) ~[na:1.8.0_25]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509) ~[na:1.8.0_25]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[na:1.8.0_25]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_25]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[na:1.8.0_25]
Wrapped by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.springframework.social.security.SocialAuthenticationServiceRegistry
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:67) ~[spring-core-4.1.5.RELEASE.jar!/:4.1.5.RELEASE]
        at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:34) ~[spring-core-4.1.5.RELEASE.jar!/:4.1.5.RELEASE]
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:50) ~[spring-data-redis-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:146) ~[spring-data-redis-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:128) ~[spring-data-redis-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
        at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:85) ~[spring-data-redis-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
Wrapped by: org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.springframework.social.security.SocialAuthenticationServiceRegistry
        at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:52) ~[spring-data-redis-1.4.2.RELEASE.jar!/:1.4.2.RELEASE]
```

I don't see any other problems except the log but I prefer to report it if someone had an idea about it ?

**Comment by UnspeakableHorror** [comment] 2015-09-26 03:55
Same here. But I'm getting it all the time, I can't login at all. Did you ever find out what caused it?

**Comment by UnspeakableHorror** [comment] 2015-09-26 04:49
Upgraded to the latest version, 1.1.2 and the problem is solved.

**Comment by vpavic** [comment] 2019-01-20 11:40
Closing as it appears to be a non-issue according to last comment. If you still experience the problem, please comment back and we can re-open the issue.

**Closed by vpavic** 2019-01-20 11:40 UTC
