### ISSUE TITLE
Consider possibility exclude PropertySourcesPlaceholderConfigurer in RedisHttpSessionConfiguration in version 1.3.x

### ISSUE THREAD

**Issue by andreytkachuk31** [spring-projects/spring-session#1259] opened 2018-11-19 12:12 UTC
**Conditions:**
We used _spring-session_ module of version 1.1.x. And we had own `PropertySourcesPlaceholderConfigurer` bean with field `ignoreUnresolvablePlaceholders=true` configured with `<context:property-placeholder ignore-unresolvable="true">`

**Issue:**
We had to upgrade _spring-session_ to 1.3.x version. We did it and we tried to run application but we got exception, because our unresolved properties were failed. It happened because there is `RedisHttpSessionConfiguration` in 1.3.x version and this configuration declares `PropertySourcesPlaceholderConfigurer` bean with field `ignoreUnresolvablePlaceholders = false`.

Could you consider possibility exclude or make optional bean `PropertySourcesPlaceholderConfigurer` in class `RedisHttpSessionConfiguration` in _spring-session_ module of 1.3.x version?

**Comment by rwinch** [comment] 2018-11-19 19:05
@andreytkachuk31 Thanks for the report.

@vpavic I am wondering if the best approach would be ignore unresolved properties. Thoughts?

**Comment by vpavic** [comment] 2018-11-19 20:46
We've removed the use of in Spring Sesion 2.0 via #907 and #910.

For 1.3, this is basically a duplicate of #867 - @andreytkachuk31, can you take a look at [this comment](https://github.com/spring-projects/spring-session/issues/867#issuecomment-328095462) and see if the proposed workaround helps?

**Comment by andreytkachuk31** [comment] 2018-11-20 12:47
@rwinch @vpavic Proposed workaround helps. Thanks!

**Comment by vpavic** [comment] 2018-11-20 12:54
Thanks for following up @andreytkachuk31 - glad to hear you were able to work around it.

**Closed by vpavic** 2018-11-20 12:54 UTC
Labels: question
