### ISSUE TITLE
Cleaning of PRINCIPAL_NAME_INDEX_NAME keys in REDIS CLUSTER

### ISSUE THREAD

**Issue by michal-kroliczek** [spring-projects/spring-session#1779] opened 2021-01-22 14:57 UTC
Hi,

our keys "spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:XXX" are not being cleaned up. 

I investigated a bit, found other issues like this, checked source of RedisHttpSessionConfiguration and I stacked when I read part of redis documentation:

> Every node of a Redis cluster generates events about its own subset of the keyspace as described above. However, unlike regular Pub/Sub communication in a cluster, events' notifications are not broadcasted to all nodes. Put differently, keyspace events are node-specific. This means that to receive all keyspace events of a cluster, clients need to subscribe to each of the nodes.

Is this supported by Spring Session? RedisMessageListenerContainer is used to subscribe to these events and if I am not mistaken this is done only to one Redis node. This way it is totally legitimate to have Redis nodes with no subscriptions to sessions expiration events.

**Comment by eleftherias** [comment] 2021-02-16 11:07
Thanks for reaching out @michal-kroliczek. I will close this as a duplicate of gh-1715 since you mentioned it is the same issue.

**Closed by eleftherias** 2021-02-16 11:07 UTC
Labels: status: waiting-for-triage, type: bug
