### ISSUE TITLE
session collision in two application contexts?

### ISSUE THREAD

**Issue by bilak** [spring-projects/spring-session#543] opened 2016-06-07 16:11 UTC
Hello,
I have [following project](https://github.com/bilak/double-oauth2) where are few applications which should share the session.
the entry point for all of them is the gateway. When user access the gateway he is redirected to the authorization server to authorize. After successful authorization user is redirected back to the gateway but in this case authorization against authorization server fails because there are two sessions available.

More about this can be found [here](https://github.com/bilak/double-oauth2)

**Comment by rwinch** [comment] 2016-06-07 16:13
Thanks for the report @bilak This appears to be a duplicate of #275 Can you confirm?

**Comment by bilak** [comment] 2016-06-07 16:18
@rwinch yes it's the same issue.

**Comment by rwinch** [comment] 2016-06-07 21:15
Thanks @bilak! Closing this as a duplicate

**Closed by rwinch** 2016-06-07 21:15 UTC
Labels: duplicate
