### ISSUE TITLE
session access issues

### ISSUE THREAD

**Issue by slacrey** [spring-projects/spring-session#144] opened 2015-02-12 02:24 UTC
By http: // localhost:? Adding session 8080 / _s = 1 link, the first page of the session cookies does not _s

**Comment by rwinch** [comment] 2015-02-12 02:57
Can you please clarify what the issue is?

**Comment by slacrey** [comment] 2015-02-12 03:56
so sorry,please view the http://docs.spring.io/spring-session/docs/current/reference/html5/guides/users.html#adding-a-session, first visit http://localhost:8080/?_s=1,inside the browser is no such "1 69c00682-d12d-45d7-bc43-d8500c44cb52" cookie. again there will be a browser cookie.

**Comment by rwinch** [comment] 2015-02-12 04:03
This is still very vague. Please provide a detailed explanation of your issue.

NOTE: The docs do not state to first visit that URL. First you should already have a session. Then, you should visit that URL. Please try [Exploring the users Sample Application](http://docs.spring.io/spring-session/docs/current/reference/html5/guides/users.html#exploring-the-users-sample-application) and look at the cookies after you have added a second user.

**Comment by rwinch** [comment] 2015-04-15 19:13
Marking this as closed and invalid due to lack of details. Please create a new issue if you have concrete case for reproducing an issue.

**Closed by rwinch** 2015-04-15 19:13 UTC
Labels: question
