### ISSUE TITLE
Issue with JSF Primefaces

### ISSUE THREAD

**Issue by louvelg** [spring-projects/spring-session#291] opened 2015-09-20 18:51 UTC
Hi,

I have an issue with spring session in a project with spring boot, JSF and Primefaces.
If I have don't have @EnableRedisHttpSession in my spring boot config, my page works fine, but if i have @EnableRedisHttpSession, I have this error :

javax.faces.application.ViewExpiredException: viewId:/groupe/groupeCreate.xhtml - La vue «/groupe/groupeCreate.xhtml» n’a pas pu être restaurée.
    at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:212)
    at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
    at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123)
    at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
    at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:59)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
    at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:109)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
    at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
    at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
    at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
    at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:41)
    at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:268)
    at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:125)
    at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:65)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:116)
    at org.springframework.boot.context.web.ErrorPageFilter.access$000(ErrorPageFilter.java:60)
    at org.springframework.boot.context.web.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:91)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:109)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Unknown Source)

This occured on a simple page with a requestScopeBean :

My page : 

``` html
<ui:param name="b" value="#{groupeCreateView}" />
<h:form id="FormContent">
            <div class="wrapper wrapper-content">
                <div class="ibox">
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-lg-12">
                                <p:messages closable="true" />
                            </div>
                        </div>
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label> <h:outputText value="#{message.groupe_name} : " /><h:outputText styleClass="requiredField" value=" *" />
                                        </label>
                                        <h:inputText value="#{b.groupe.name}" required="true" label="#{message.groupe_name}" styleClass="form-control" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label> <h:outputText value="#{message.groupe_description} : " />
                                        </label>
                                        <h:inputTextarea value="#{b.groupe.description}"  label="#{message.groupe_description}" styleClass="form-control">
                                            <f:validateLength maximum="65000"></f:validateLength>
                                        </h:inputTextarea>
                                    </div>
                                </div>
                            </div>

                        <div class="row">
                            <div class="col-lg-12">
                                <div class="submit-btns-zone pull-right">
                                    <h:link outcome="pretty:viewGroupeList" styleClass="btn btn-white">
                                        <h:outputText value="#{message.cancel}" />
                                    </h:link>
                                    <h:commandLink action="#{b.createGroupe}" styleClass="btn btn-primary">
                                        <h:outputText value="#{message.save}" />
                                    </h:commandLink>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </h:form>
```

And my JSF Bean : 

``` java
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import org.springframework.beans.factory.annotation.Autowired;
import com.ocpsoft.pretty.faces.annotation.URLMapping;

@RequestScoped
@ManagedBean(name = "groupeCreateView")
@URLMapping(id = "viewGroupeCreate", pattern = "/groupe/create", viewId = "/faces/groupe/groupeCreate.xhtml")
public class GroupeCreateView extends BaseView implements Serializable {

    @Autowired
    private transient GroupeService groupeService;

    private Groupe                  groupe;

    @PostConstruct
    public void init() {
        initBean();
        groupe = new Groupe();
    }

    public String createGroupe() {
        groupe.setTenantId(getTenantId());
        groupeService.createGroupe(getUser(), groupe);
        return "pretty:viewGroupeList";
    }

    public Groupe getGroupe() {
        return groupe;
    }

    public void setGroupe(Groupe groupe) {
        this.groupe = groupe;
    }
}
```

My initBean method : 

``` java
public void initBean() {
        WebApplicationContextUtils.getRequiredWebApplicationContext((ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext()).getAutowireCapableBeanFactory()
                .autowireBean(this);
    }
```

Can you help me to find or correct this issue.

**Comment by rwinch** [comment] 2015-10-02 18:44
Thanks for the report. Can you put together a sample to reproduce this?

**Comment by Pilli** [comment] 2016-01-01 20:00
Hi.

I had the same problem with facelets, JSF managed bean, spring managed bean and spring session. I think i had this issue because JSF store form component's state in server (session).
I fix it adding this lines to web.xml:
```
<context-param>
	<param-name>javax.faces.STATE_SAVING_METHOD</param-name>
	<param-value>client</param-value>
</context-param>
```
Now, JSF store component's state in hidden input field.

Gradle project with example, uses JSF managed beans and Spring managed beans. [jsf.zip](https://github.com/spring-projects/spring-session/files/76015/jsf.zip)

More info:
* http://stackoverflow.com/questions/5474316/why-jsf-saves-the-state-of-ui-components-on-server/5475564#5475564
* http://stackoverflow.com/questions/3642919/javax-faces-application-viewexpiredexception-view-could-not-be-restored
* http://stackoverflow.com/questions/19382070/keep-getting-javax-faces-application-viewexpiredexception-viewid-with-jsf-2

Best regards.

**Comment by joragupra** [comment] 2016-06-16 13:32
I am experiencing this problem, too. In my case, `javax.faces.STATE_SAVING_METHOD` is `server`, and it does not work when I try to use spring-session in my project.

**Comment by MarceloNunesAlves** [comment] 2018-01-11 16:46
@joragupra Did you solve the session problem? I'm trying to use spring-session with Redis in an existing application and I'm also having this problem.

**Comment by spring-issuemaster** [comment] 2020-12-15 17:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-22 17:43
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-22 17:43 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
