### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [spring-projects/spring-session#2231] opened 2023-02-05 11:56 UTC
## Description

In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by marcusdacoregio** [comment] 2023-02-08 13:36
Thanks a lot, @jongwooo, there is another PR for fixing this, so I'll close this as a duplicate of #2226.

**Closed by marcusdacoregio** 2023-02-08 13:36 UTC
Labels: type: enhancement, status: waiting-for-triage
