### ISSUE TITLE
Spring Session Redis is not clearing expired  index to sessions in Redis

### ISSUE THREAD

**Issue by git-syl** [spring-projects/spring-session#2166] opened 2022-09-22 13:57 UTC
**Describe the bug**
I integrated Spring Session into my project. 
I found that the Spring Boot (Servlet container)  and spring boot WebFlux (reactor project )integrated Spring sessions at the same time, which caused the redis key to not expire. 

spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:
spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:
spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:
...
In Redis many keys failed to clean, resulting in memory overflow.

And My  Spring Boot (Servlet container) Application with some WARN  :
_**2022-09-22 17:11:33.171  WARN 23620 --- [nerContainer-49] o.s.s.d.r.RedisIndexedSessionRepository  : Unable to publish SessionDestroyedEvent for session 727ae15d-7f42-4f8d-b229-f8385ac54b06**_

**To Reproduce**

spring boot 2.6.11
spring-session-data-redis  2.6.3

STEP-01 : Login and get token, in login project  , it is  Spring Boot applicaiton (Servlet container)
STEP-02 : Access RESTFUL api  in reactor project  immediately.
STEP-03 : Wait abount 30 seconds and view logs. Or look`t the data in Redis
test code like :
```
@Test
void test(){

 String XAuthToken = login(userName);

    for (int i = 0; i < 10; i++) {
            new Thread(new HttpClientPost( XAuthToken)).start();
        }
}
```

**Expected behavior**

Automatically clean keys (spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:),
when the session expires.

**Sample**

https://github.com/sunyl-git/sunyl-git-spring-reactor-session-issue-report-sample

In my limited experience with Spring, Thanks in advance!

**Comment by baozi-2019** [comment] 2023-04-14 02:15
I have the same problem, do you have a solution?

**Comment by git-syl** [comment] 2023-04-15 05:17
> I have the same problem, do you have a solution?

从反应式项目中禁用spring session redis。
自己写个token拦截器，从Redis查询并验证当前登录信息，然后手动设置到SpringSecurityContext里面。

disabled spring session redis is in Reactor project.
Add an token interceptor that queries from redis and binds it to the spring security context.

**Comment by marcusdacoregio** [comment] 2023-10-16 18:27
Hi, @git-syl. Thanks for the report.

I'm confused, we do not have an indexed Redis implementation for Reactive, therefore it is not possible to have a `spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME` created by Spring Session Redis. Can you elaborate more on that?

**Comment by git-syl** [comment] 2023-10-24 05:19
> Hi, @git-syl. Thanks for the report.
> 
> I'm confused, we do not have an indexed Redis implementation for Reactive, therefore it is not possible to have a `spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME` created by Spring Session Redis. Can you elaborate more on that?
> 
> Your sample has too many things going on, can you make it minimal?

Hi @marcusdacoregio ,Thank you for your response. 
I have removed other unrelated dependencies from the project. To reproduce this issue, at least two projects need to be run- together. One is a login project based on servlet, and the other is a gateway project based on spring webflux. When accessing the interface of the reactor-project project, ReactiveRedisSessionRepository is triggered (`located at: org\springframework\session\spring-session-data-redis\2.6.3\spring-session-data-redis-2.6.3.jar!\org\springframework\session\data\redis\ReactiveRedisSessionRepository.class`). 

I speculate that there is some code inside ReactiveRedisSessionRepository(spring-session-data-redis-2.6.3.jar) to renew the redisKey & Modifying the redisKey causes the login project to be unable to clear the redis key.
After calling the interface of the login project, immediately access the interface of the reactor-project. You can reproduce this result.
(run the SessionTest test case.
`login\src\test\java\com\zhichanzaixian\trademarkapi\SessionTest.java`)

**Comment by marcusdacoregio** [comment] 2023-10-24 12:07
Hello, @git-syl. Which Redis keys are you talking about? Is it the index key (which should not exist in the reactive implementation), or is it the session key? It is important to note that Redis may [not remove all expired keys instantly](https://redis.io/commands/expire/#:~:text=Redis%20keys%20are%20expired%20in,will%20never%20be%20accessed%20again.). In addition to that, [there was a bug](https://github.com/spring-projects/spring-session/issues/2464) on older versions of Spring Session Redis Reactive where it would fail to set the expiration time to a key.

**Comment by git-syl** [comment] 2023-10-24 15:34
> Hello, @git-syl. Which Redis keys are you talking about? Is it the index key (which should not exist in the reactive implementation), or is it the session key? It is important to note that Redis may [not remove all expired keys instantly](https://redis.io/commands/expire/#:~:text=Redis%20keys%20are%20expired%20in,will%20never%20be%20accessed%20again.). In addition to that, [there was a bug](https://github.com/spring-projects/spring-session/issues/2464) on older versions of Spring Session Redis Reactive where it would fail to set the expiration time to a key.

It is the index key. After accessing the index key in this class, the index key will persist indefinitely and won't be automatically cleared.(Even if the project is set with spring.session.timeout=20s)
Its source code is located at :
[ReactiveRedisSessionRepository](https://github.com/spring-projects/spring-session/blob/e19beec5eaf93dee75777e588fe2a234c0594bd9/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/ReactiveRedisSessionRepository.java#L49C2-L49C2)

If I'm not mistaken, under normal circumstances, the index key `spring:session:index:org.springframework.session.FindByIndexNameSessionRepository.PRINCIPAL_NAME_INDEX_NAME:user_name` should expire automatically.

Other servlet projects will receive a large number of failed clean-up logs, and the source code is located at：
[RedisIndexedSessionRepository](https://github.com/spring-projects/spring-session/blob/e19beec5eaf93dee75777e588fe2a234c0594bd9/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L546)

Thank you very much in the end. I appreciate you mentioning issue #2464. 
I plan to find some time to experiment with it, as it could possibly be the same issue

**Comment by marcusdacoregio** [comment] 2023-10-25 17:02
I'm a bit confused because you mentioned Spring WebFlux apps and the problem is related to the index key which is created by an indexed session repository implementation, in that case, `RedisIndexedSessionRepository`, which is not available on the reactive side.

The [Redis documentation for expire says](https://redis.io/commands/expire/#:~:text=How%20Redis%20expires%20keys,will%20never%20be%20accessed%20again.):

> Redis keys are expired in two ways: a passive way, and an active way.
A key is passively expired simply when some client tries to access it, and the key is found to be timed out.
Of course this is not enough as there are expired keys that will never be accessed again.

That means that even if the key is expired, it might not be instantly removed from the database. The `RedisIndexedSessionRepository` implementation [depends on Redis events to be able to delete the indexes](https://github.com/spring-projects/spring-session/blob/5225bd1796c3d839005db506ad95d9e7596543f7/spring-session-data-redis/src/main/java/org/springframework/session/data/redis/RedisIndexedSessionRepository.java#L589-L615) since they do not have an expiration time themselves. If your Redis instance is not configured to emit events, then those keys won't be cleaned up. More details on [the documentation](https://docs.spring.io/spring-session/reference/api.html#api-redisindexedsessionrepository-expiration).

I'll close this since it appears that the behavior is expected, if you still think that this is a bug in Spring Session, please add a **minimal, reproducible sample** where we can debug the behavior consistently.

**Closed by marcusdacoregio** 2023-10-25 17:02 UTC
Labels: type: bug, status: feedback-provided
