### ISSUE TITLE
Spring + DevTool + Redis Session: Serializer doesn't work

### ISSUE THREAD

**Issue by genesiskoo** [spring-projects/spring-session#536] opened 2016-06-02 02:41 UTC
Hi,
I am having trouble combination with 
spring boot 1.3.3 , spring session, session-redis 1.0.2, jedis 2.8.1

Here is configration for radis
`@Configuration
@EnableRedisHttpSession
public class HttpSessionConfig {
    @Value("${spring.redis.timeout}")
    private int timeout;

    StringRedisSerializer stringRedisSerializer = new StringRedisSerializer(StandardCharsets.UTF_8);

    @Primary
    @Bean
    public RedisTemplate<String, ExpiringSession> sessionRedisTemplate(RedisConnectionFactory jedisConnectionFactory) {
        RedisTemplate<String, ExpiringSession> template = new RedisTemplate<>();
        template.setConnectionFactory(jedisConnectionFactory);
        template.setDefaultSerializer(stringRedisSerializer);
        template.setKeySerializer(stringRedisSerializer);
        template.setHashKeySerializer(stringRedisSerializer);
        template.setValueSerializer(new GenericJackson2JsonRedisSerializer());
        template.setHashValueSerializer(new GenericJackson2JsonRedisSerializer());

        return template;
    }

    @Bean
    public RedisOperationsSessionRepository sessionRepository(RedisTemplate<String, ExpiringSession> sessionRedisTemplate) {
        RedisOperationsSessionRepository sessionRepository = new RedisOperationsSessionRepository(sessionRedisTemplate);
        sessionRepository.setDefaultMaxInactiveInterval(timeout);
        return sessionRepository;
    }
}`

in this case,
except DefaultSerializer, All RedisSerializer changed to RestartCompatibleRedisSerializer
and it doesn't work because with DevTool, it gave me the result with prefix 

Here is the result when devTool is running and isn't

=======================================================
DevTool running
======================================================
127.0.0.1:6379> keys '*'
1) "spring:session:expirations:1551200880000"
2) "\xac\xed\x00\x05t\x00(spring:session:expirations:1551200640000"
3) "\xac\xed\x00\x05t\x00<spring:session:sessions:1c90bbc0-fd87-467b-9fbb-890c81b57fd6"
4) "spring:session:sessions:77d1f9e0-b24c-4c7b-acfe-5dab8136f1d3"
127.0.0.1:6379> shutdown
not connected> [1]  + 25108 done       nohup redis-server
======================================================
DevTool isn't running
======================================================
➜  3.0.7 git:(master) rm -f dump.rdb      
➜  3.0.7 git:(master) nohup redis-server &
[1] 25199
appending output to nohup.out                                                                                                                          
➜  3.0.7 git:(master) redis-cli           
127.0.0.1:6379> keys '*'
(empty list or set)
127.0.0.1:6379> keys '*'
1) "spring:session:expirations:1551200940000"
2) "spring:session:sessions:fa08dbce-6b8f-4e60-90e0-fe97782c75b8"
127.0.0.1:6379> keys '*'
1) "spring:session:sessions:fa08dbce-6b8f-4e60-90e0-fe97782c75b8"
2) "spring:session:expirations:1551201120000"
127.0.0.1:6379> 
======================================================

**Comment by rwinch** [comment] 2016-06-14 21:48
Thanks for the report! This appears to be a duplicate of https://github.com/spring-projects/spring-boot/issues/5760 This should be resolved in the latest Spring Boot 1.4 snapshots. See https://github.com/spring-projects/spring-boot/issues/6058#issuecomment-225907055

**Closed by rwinch** 2016-06-14 21:48 UTC
