### ISSUE TITLE
Using spring-session-data-redis causes not working of commons fileupload

### ISSUE THREAD

**Issue by rogue2yjg** [spring-projects/spring-session#617] opened 2016-09-08 03:25 UTC
We have a Spring Boot application using spring-session-data-redis 1.2.1.RELEASE. Also we use commons fileupload. But spring session data redis rewrite HttpServletRequest and delete our file stream before entering our Controller when we uploading files. Besides the filter of spring session data redis owns highest priority. The result is MultipartFile param of our Controller is null.
How can we solve the problem?

**Comment by rwinch** [comment] 2016-09-08 14:12
Thanks for the report! Any chance you can submit a sample to reproduce this?

**Comment by panchenko** [comment] 2016-11-05 04:17
This could be similar to #649

**Comment by satyajit-burman** [comment] 2017-04-14 07:24
I am using RedisSession in my project, when I am trying to import import org.springframework.session.data.redis.RedisOperationsSessionRepository.RedisSession;

Its showing:
"The type org.springframework.session.data.redis.RedisOperationsSessionRepository.RedisSession is not visible"
If it is not visible then how we can use it?

**Comment by spring-issuemaster** [comment] 2020-12-15 17:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-12-22 17:43
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-12-22 17:43 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
