### ISSUE TITLE
Add useEntryProcessor flag into HazelcastIndexedSessionRepository to avoid using remote user code deployment

### ISSUE THREAD

**Issue by shustinho** [spring-projects/spring-session#2463] opened 2023-10-05 19:16 UTC
**Expected Behavior**

We should have a choise for session replication in HZ whether we want to execute code on client side or on cluster member. Add useEntryProcessor flag into HazelcastIndexedSessionRepository and do non atomic map.get(), map.put() in case of useEntryProcessor is false. Change should be made here HazelcastIndexedSessionRepository#save

**Current Behavior**

Right now client should provide classes to HZ member for remote execution. But simple http session replication is litghweight operation that can be executed on client side. Remote code deployment lead to a lot of restrictions and should be made by a valuable reason.

**Context**
So client couple with HZ instance and require the same JDK version as a minimum. I am not sure about difference spring versions.

**Comment by marcusdacoregio** [comment] 2023-10-09 10:53
Hi, @shustinho. Thanks for the suggestion.

Do you mean that if the flag is `true` we should do something like:

```java
this.sessions.set(session.getId(), session.getDelegate(), session.getMaxInactiveInterval().getSeconds(),
					TimeUnit.SECONDS);
```

instead of using the `EntryProcessor` do apply the update?

**Comment by shustinho** [comment] 2023-10-09 12:46
Yes, @marcusdacoregio

**Comment by marcusdacoregio** [comment] 2023-10-09 17:30
I think this is a duplicate of https://github.com/spring-projects/spring-session/issues/1131. If we improve the serialization mechanism by using `Portable`, for example, we wouldn't need to add a flag to control the strategy used for session updates. Maybe we can add such an implementation in https://github.com/spring-projects/spring-session/pull/1174 and port it to the servlet version.

That said, I will close this as a duplicate of #1131.

**Closed by marcusdacoregio** 2023-10-09 17:30 UTC
Labels: type: enhancement, in: hazelcast
