### ISSUE TITLE
SessionDestroyedEvent does not receive session expired event for Redis cluster

### ISSUE THREAD

**Issue by ohHyunJae** [spring-projects/spring-session#2175] opened 2022-10-07 09:06 UTC
ExpiredEvent seems to be lost..... if we use redis cluster. 
It works perfect if we use a stand-alone redis server.

my redis.config
notify-keyspace-events "Egx"
<img width="224" alt="image" src="https://user-images.githubusercontent.com/18163630/194514845-275d50b2-d92f-4131-9814-f86cde2bcff6.png">

my project code
```

implementation 'org.springframework.session:spring-session-data-redis:2.7.0'
implementation 'org.springframework.data:spring-data-redis:2.7.3'
implementation 'io.lettuce:lettuce-core:6.1.8.RELEASE'

@Configuration
@EnableRedisHttpSession(maxInactiveIntervalInSeconds = 60 * 1)
@EnableRedisRepositories
public class RedisConfig {
      @Bean
    public LettuceConnectionFactory lettuceConnectionFactory() {
        RedisClusterConfiguration redisClusterConfiguration
                = new RedisClusterConfiguration(
                        List.of("ip:port", "ip:port", "ip:port"));
        redisClusterConfiguration.setPassword("password");
        return new LettuceConnectionFactory(redisClusterConfiguration);
   }
}
```

```
@Component
public class RedisSessionListener {
    @EventListener
    public void onCreate(org.springframework.session.events.SessionCreatedEvent event) {
        System.out.println("create!!");
        System.out.println(event);
    }

    @EventListener
    public void onDestroy(org.springframework.session.events.SessionDestroyedEvent event) {
        System.out.println("destory!!");
        System.out.println(event);
    }

    @EventListener
    public void sessionExired(SessionExpiredEvent event) {
        System.out.println("exired!!");
        System.out.println(event);
    }
}
```

I repeated log in and log out

test result..
![image](https://user-images.githubusercontent.com/18163630/194516417-b31aba82-376a-41f8-ab12-866e32a8c1f3.png)

As it's seem like the expired event seems to be lost.

Is there a solution?

**Comment by saefty** [comment] 2023-01-02 16:04
We are running into the same issue. According to the redis cluster documentation keyspace events are node specific. They are not propagated across the cluster. Therefore spring-session might not subscribe to those notifications on all primary shards?

I was only able to reproduce the problem when we incrased the shard count above 1.

https://redis.io/docs/manual/keyspace-notifications/

> Every node of a Redis cluster generates events about its own subset of the keyspace as described above. However, unlike regular Pub/Sub communication in a cluster, events' notifications are not broadcasted to all nodes. Put differently, keyspace events are node-specific. This means that to receive all keyspace events of a cluster, clients need to subscribe to each of the nodes.

**Comment by marcusdacoregio** [comment] 2023-02-06 16:35
Hi @ohHyunJae, thanks for the report.

I believe this is a duplicate of https://github.com/spring-projects/spring-session/issues/2230. I think you should follow [this same guidance](https://github.com/spring-projects/spring-session/issues/2230#issuecomment-1410796814) and add your use case to the referenced issue.

**Closed by marcusdacoregio** 2023-02-06 16:35 UTC
Labels: type: bug, status: waiting-for-triage
