### ISSUE TITLE
Received status code 401 from server: Unauthorized with junit-bom-5.7.0

### ISSUE THREAD

**Issue by darkoni** [spring-projects/spring-session#1815] opened 2021-04-09 21:04 UTC
**Describe the bug**

When compiling the project from source I get  __Received status code 401 from server: Unauthorized__

**To Reproduce**

As __cloning from repository does not work__, I use wget
```
wget https://github.com/spring-projects/spring-session/archive/2.4.2.zip
unzip 2.4.2.zip
cd spring-session-2.4.2
./gradlew install
```
The output I get is:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/username/JavaTest/SpringBootSession/spring-session-2.4.2/spring-session-docs/spring-session-docs.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':spring-session-docs'.
> Could not resolve all dependencies for configuration ':spring-session-docs:detachedConfiguration1'.
   > Could not resolve org.junit:junit-bom:5.7.0.
     Required by:
         project :spring-session-docs
      > Could not resolve org.junit:junit-bom:5.7.0.
         > Could not get resource 'https://repo.spring.io/libs-release/org/junit/junit-bom/5.7.0/junit-bom-5.7.0.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-release/org/junit/junit-bom/5.7.0/junit-bom-5.7.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve org.testcontainers:testcontainers-bom:1.15.1.
     Required by:
         project :spring-session-docs
      > Could not resolve org.testcontainers:testcontainers-bom:1.15.1.
         > Could not get resource 'https://repo.spring.io/libs-release/org/testcontainers/testcontainers-bom/1.15.1/testcontainers-bom-1.15.1.pom'.
            > Could not HEAD 'https://repo.spring.io/libs-release/org/testcontainers/testcontainers-bom/1.15.1/testcontainers-bom-1.15.1.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```
**Expected behavior**

I expect no error :-)

Instead I get __Received status code 401 from server: Unauthorized__

Please, advise me on what to do.

Many thanks !

**Comment by eleftherias** [comment] 2021-04-12 15:40
Thanks for reaching out @darkoni.
This looks like a duplicate of gh-1792.
There is a workaround listed in that issue that may help with the error you are getting.

**Closed by eleftherias** 2021-04-12 15:40 UTC
Labels: status: waiting-for-triage, type: bug
