### ISSUE TITLE
Provide a way to react to serialization exceptions with Redis http session

### ISSUE THREAD

**Issue by sazonov** [spring-projects/spring-session#1339] opened 2019-02-26 12:41 UTC
Hi.
JdkSerializationRedisSerializer generates many deserialization issues. There are deserialization exceptions when I move UserPrincipal to another package or when some Spring Security serialization id is changed. Could you please provide a way to react to this exceptions and for example to reset user session.
I found a way to do so by modifying RedisOperationsSessionRepository#getSession but it is quite hard to do because of private methods and it seems that it is not supposed to be modified that way.
It will be usesfull for all session Serializers.
Thanks.

spring-session-data-redis 2.1.4.RELEASE

**Comment by vpavic** [comment] 2019-05-10 21:09
Thanks for the report - this looks like a duplicate of #529.

**Comment by vpavic** [comment] 2019-05-13 17:13
Duplicate of #529

**Closed** 2019-05-13 17:13 UTC
